### ISSUE TITLE
NPE when changing replication factor

### ISSUE THREAD

**Issue by martinplank** [linkedin/cruise-control#1074]
I tried to increase topic's replication factor with the REST API request:
```
curl -X POST "http://[hostname]/kafkacruisecontrol/topic_configuration?topic=test&replication_factor=2"
```
but it failed with NPE:
```
[2020-01-24 13:08:53,949] INFO Processing async request TopicConfigurationRequest. (com.linkedin.kafka.cruisecontrol.servlet.handler.async.AbstractAsyncRequest)
[2020-01-24 13:08:53,950] INFO Create a new UserTask 4c0efeed-c621-4849-acc7-de07a7217142 with SessionKey SessionKey{_httpSession=Session@3b1588b8{id=node01q9w705xf33hk1jnp9q5p586zy2,x=node01q9w705xf33hk1jnp9q5p586zy2.node0,req=1,res=true},_requestUrl=POST /kafkacruisecontrol/topic_configuration,_queryParams={replication_factor=[2], topic=[test]}} (com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager)
[2020-01-24 13:08:53,967] WARN Received exception when trying to execute runnable for "Update Topic Configuration" (com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable)
com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.updateTopicReplicationFactor(UpdateTopicConfigurationRunnable.java:224)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:67)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:49)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.run(UpdateTopicConfigurationRunnable.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createReplica(ClusterModel.java:796)
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createOrDeleteReplicas(ClusterModel.java:943)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.updateTopicReplicationFactor(UpdateTopicConfigurationRunnable.java:199)
	... 9 more
[2020-01-24 13:08:53,968] ERROR Error processing POST request '/topic_configuration' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException'. (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)
java.util.concurrent.ExecutionException: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.AbstractAsyncRequest.getResponse(AbstractAsyncRequest.java:57)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.AbstractRequest.handle(AbstractRequest.java:40)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.handlePost(KafkaCruiseControlServlet.java:215)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGetOrPost(KafkaCruiseControlServlet.java:123)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doPost(KafkaCruiseControlServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.updateTopicReplicationFactor(UpdateTopicConfigurationRunnable.java:224)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:67)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:49)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.run(UpdateTopicConfigurationRunnable.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createReplica(ClusterModel.java:796)
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createOrDeleteReplicas(ClusterModel.java:943)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.updateTopicReplicationFactor(UpdateTopicConfigurationRunnable.java:199)
	... 9 more
[2020-01-24 13:08:54,860] WARN UserTask 4c0efeed-c621-4849-acc7-de07a7217142 is completed with Exception and removed from active tasks list (com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager)
[2020-01-24 13:08:54,861] INFO Task [4c0efeed-c621-4849-acc7-de07a7217142] calculation fails, exception:
{} (operationLogger)
java.util.concurrent.ExecutionException: Operation 'Update Topic Configuration' received exception. com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationFuture.get(OperationFuture.java:49)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager$UserTaskInfo.logOperation(UserTaskManager.java:744)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager$UserTaskInfo.access$100(UserTaskManager.java:618)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager.lambda$checkActiveUserTasks$1(UserTaskManager.java:348)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.updateTopicReplicationFactor(UpdateTopicConfigurationRunnable.java:224)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:67)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:49)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.run(UpdateTopicConfigurationRunnable.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createReplica(ClusterModel.java:796)
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createOrDeleteReplicas(ClusterModel.java:943)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.updateTopicReplicationFactor(UpdateTopicConfigurationRunnable.java:199)
```

version: 2.0.87

Deployed on OpenShift with Strimzi cluster. I followed this guide: https://strimzi.io/2019/09/03/hacking-for-cruise-control.html

Related to #853

anyone knows what is causing this error?

**Comment by kidkun** [comment]
@martinplank  Can you check that the brokers in your cluster have `rack` information properly populated?
you can check through znode /brokers/ids/broker_id
I suspect the reason why you get NPE is because in the metadata CC retrieves from Kafka, some broker's rack information is missing

**Comment by Eric-L90** [comment]
any update?
