### ISSUE TITLE
More useful error message in KafkaCruiseControlMain.java

### ISSUE THREAD

**Issue by kyrsideris** [linkedin/cruise-control#1129]
[KafkaCruiseControlMain.java](https://github.com/linkedin/cruise-control/blob/2.0.92/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlMain.java#L37) is capturing and silencing problems with the configuration file. In my case, the path of `config/capacityJBOD.json` was not clear to the start up script. It would be useful to have more helpful error messages than 
```
USAGE: java KafkaCruiseControlMain cruisecontrol.properties [port] [ipaddress|hostname]
```

After patching the code to print the call stack, the problem was revealed:
```java
java.lang.IllegalArgumentException: java.io.FileNotFoundException: config/capacityJBOD.json (No such file or directory)
	at com.linkedin.kafka.cruisecontrol.config.BrokerCapacityConfigFileResolver.configure(BrokerCapacityConfigFileResolver.java:163)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:66)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:159)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:128)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:112)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:34)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlApp.<init>(KafkaCruiseControlApp.java:43)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:34)
Caused by: java.io.FileNotFoundException: config/capacityJBOD.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.linkedin.kafka.cruisecontrol.config.BrokerCapacityConfigFileResolver.loadCapacities(BrokerCapacityConfigFileResolver.java:296)
	at com.linkedin.kafka.cruisecontrol.config.BrokerCapacityConfigFileResolver.configure(BrokerCapacityConfigFileResolver.java:161)
	... 7 more
```

**Comment by efeg** [comment]
@kyrsideris  Thanks for taking time to report this issue! Would you be interested in submitting a PR for the fix?

**Comment by kyrsideris** [comment]
Thanks for your reply. Sure I will!

**Comment by efeg** [comment]
This issue was addressed in https://github.com/linkedin/cruise-control/pull/1173.
