### ISSUE TITLE
I am getting the below error in cruise control

### ISSUE THREAD

**Issue by ankurggbpec** [linkedin/cruise-control#1170]
ERROR Sampling scheduler received Timeout exception when waiting for sampling to finish. (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager)
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.fetchSamples(MetricFetcherManager.java:208)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.fetchPartitionMetricSamples(MetricFetcherManager.java:165)
        at com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask.run(SamplingTask.java:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Also getting below errors while fetching the kafka cluster state
ERROR: Error processing GET request '/kafka_cluster_state' due to: 'Failed to populate broker logDir state.'.

**Comment by efeg** [comment]
Hi @ankurggbpec 
Could you share the version of (1) Kafka and (2) Cruise Control are you using? Are these transient or permanent errors?

**Comment by efeg** [comment]
Closing the issue. @ankurggbpec please feel free to reopen if you have more details.
