### ISSUE TITLE
topic_configuration, java.lang.NullPointerException

### ISSUE THREAD

**Issue by Eric-L90** [linkedin/cruise-control#1175]
full stack trace:
`java.util.concurrent.ExecutionException: Operation 'Update Topic Configuration' received exception. com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationFuture.get(OperationFuture.java:49)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager$UserTaskInfo.logOperation(UserTaskManager.java:744)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager$UserTaskInfo.access$100(UserTaskManager.java:618)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager.lambda$checkActiveUserTasks$1(UserTaskManager.java:348)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:132)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:152)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.getResult(UpdateTopicConfigurationRunnable.java:70)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.run(GoalBasedOperationRunnable.java:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createReplica(ClusterModel.java:796)
	at com.linkedin.kafka.cruisecontrol.model.ClusterModel.createOrDeleteReplicas(ClusterModel.java:943)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.UpdateTopicConfigurationRunnable.workWithClusterModel(UpdateTopicConfigurationRunnable.java:197)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:128)
	... 9 more`

Related to #1074

**Comment by Eric-L90** [comment]
any update?

**Comment by efeg** [comment]
@Eric-L90 Sorry for the delayed response.
The root cause of NPE is inconsistent assignment `rackID` during `topic_configuration` requests in case `rack.id` is not set in the Kafka cluster configurations. https://github.com/linkedin/cruise-control/pull/1234 will resolve this issue.
