### ISSUE TITLE
Executor got exception during execution

### ISSUE THREAD

**Issue by amuraru** [linkedin/cruise-control#1207]
I am seeing the following exception in CC logs during cluster rebalance:
```java
86971403 [posalExecutor-0] ERROR ruisecontrol.executor.Executor  - Executor got exception during execution
java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.verifyFutureError(Executor.java:1436)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.maybeMarkTaskAsDeadOrAborting(Executor.java:1407)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.waitForExecutionTaskToFinish(Executor.java:1230)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.interBrokerMoveReplicas(Executor.java:1013)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.execute(Executor.java:829)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.run(Executor.java:771)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by efeg** [comment]
@amuraru Thanks for reporting this bug!
This indeed can happen if the task execution takes longer than execution progress check interval on `Kafka 2.4.0+` deployments.
A new version with the fix will be released today.

**Comment by amuraru** [comment]
Thanks @efeg
