### ISSUE TITLE
Disable CruiseControlMetricsReporter?

### ISSUE THREAD

**Issue by ericychoi** [linkedin/cruise-control#1250]
Hi, I wanted to try out cruise control without affecting the kafka cluster first, so I followed the instruction on readme but skipped "step 1".  Now cruise control doesn't start up with the message: 
```
[2020-06-23 16:01:37,481] ERROR _metricConsumer returned null for _metricReporterTopic __CruiseControlMetrics (com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler)
Exception in thread "main" java.lang.IllegalStateException: Cruise Control cannot find partitions for the metrics reporter that topic matches __CruiseControlMetrics in the target cluster.
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.configure(CruiseControlMetricsReporterSampler.java:244)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfigUtils.getConfiguredInstance(KafkaCruiseControlConfigUtils.java:43)
```

Is there a way to start up cruise control without metrics so that I can try it out without affecting the cluster first?

**Comment by efeg** [comment]
@ericychoi You can change the following config value as `com.linkedin.kafka.cruisecontrol.monitor.sampling.NoopSampler` to be able to start Cruise Control (CC) in this mode. As the name implies, this sampler does nothing useful.

```
# The metric sampler class
metric.sampler.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler
```

In this mode, as expected, CC will be unable to collect any metrics from the cluster; hence, it will be unable to create a cluster model to be used for operations such as rebalance, remove_broker, load, and partition_load. Though, you would still be able to query endpoints such as `kafka_cluster_state` if that is what you are looking for.

**Comment by efeg** [comment]
Closing the issue. @ericychoi please feel free to reopen if you have further questions.
