### ISSUE TITLE
Deleted topic shouldn't stop the executor

### ISSUE THREAD

**Issue by RossierFl** [linkedin/cruise-control#1318]
Hi, 
While running Cruise Control for the first time, a topic that was part of a reassignment got deleted, making the executor stop the current rebalance. 

```
[2020-08-31 14:09:38] ERROR ProposalExecutor-0 Executor:1028 - Executor got exception during execution
kafka.admin.AdminOperationException: Topic "topic_name_here" does not exist.
	at kafka.zk.AdminZkClient.validateTopicConfig(AdminZkClient.scala:326)
	at kafka.zk.AdminZkClient.changeTopicConfig(AdminZkClient.scala:340)
	at com.linkedin.kafka.cruisecontrol.executor.ExecutorUtils$.changeTopicConfig(ExecutorUtils.scala:133)
	at com.linkedin.kafka.cruisecontrol.executor.ExecutorUtils.changeTopicConfig(ExecutorUtils.scala)
	at com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelper.setThrottledReplicas(ReplicationThrottleHelper.java:185)
	at com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelper.setLeaderThrottledReplicas(ReplicationThrottleHelper.java:168)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.linkedin.kafka.cruisecontrol.executor.ReplicationThrottleHelper.setThrottles(ReplicationThrottleHelper.java:54)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.interBrokerMoveReplicas(Executor.java:1156)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.execute(Executor.java:985)
	at com.linkedin.kafka.cruisecontrol.executor.Executor$ProposalExecutionRunnable.run(Executor.java:911)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-08-31 14:09:38] WARN  ProposalExecutor-0 operationLogger:1063 - Task [fde0e0e0-698a-4720-ac31-da31e5ac377e] userPOST /kafkacruisecontrol/REBALANCE execution is interrupted with exception Topic "topic_name_here" does not exist..
[2020-08-31 14:09:38] INFO  ProposalExecutor-0 Executor:912 - Execution finished.
```

Wouldn't be beneficial if the executor just skipped this topic and continue the rebalance tasks instead of stopping it ? 
Thanks in advance !

**Comment by efeg** [comment]
Hi @RossierFl thanks for reporting this!
Could you please share the version of CC you have encountered this issue?

**Comment by RossierFl** [comment]
@efeg, yes sorry forgot to mention it, it's the version 2.0.127, it's the latest one compatible with Kafka 2.3.

Thanks for the acknowledgement !
