### ISSUE TITLE
Get error when query Cruise Control state with "super_verbose" parameter set true

### ISSUE THREAD

**Issue by Lincong** [linkedin/cruise-control#1356]
Users can query Cruise Control state and request verbose information in the response. For example:

`GET http://<Cruise Control host>:<port>/kafkacruisecontrol/state?super_verbose=true`

It returns an error `Error processing GET request '/state' due to: 'matrix is singular'`

**Comment by Lincong** [comment]
Complete stack trace:

```
org.apache.commons.math3.linear.SingularMatrixException: matrix is singular
	at org.apache.commons.math3.linear.QRDecomposition$Solver.solve(QRDecomposition.java:354) ~[commons-math3-3.6.1.jar:3.6.1]
        at org.apache.commons.math3.stat.regression.OLSMultipleLinearRegression.calculateBeta(OLSMultipleLinearRegression.java:257) ~[commons-math3-3.6.1.jar:3.6.1]
        at org.apache.commons.math3.stat.regression.AbstractMultipleLinearRegression.estimateRegressionParameters(AbstractMultipleLinearRegression.java:264) ~[commons-math3-3.6.1.jar:3.6.1]
        at com.linkedin.kafka.cruisecontrol.model.LinearRegressionModelParameters.modelState(LinearRegressionModelParameters.java:203) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.model.ModelParameters.linearRegressionModelState(ModelParameters.java:76) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitorState.detailTrainingProgress(LoadMonitorState.java:358) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.response.CruiseControlState.writeSuperVerbose(CruiseControlState.java:173) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.response.CruiseControlState.getPlaintext(CruiseControlState.java:193) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.response.CruiseControlState.discardIrrelevantAndCacheRelevant(CruiseControlState.java:203) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.response.AbstractCruiseControlResponse.discardIrrelevantResponse(AbstractCruiseControlResponse.java:41) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.response.AbstractCruiseControlResponse.writeSuccessResponse(AbstractCruiseControlResponse.java:34) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.handler.AbstractRequest.handle(AbstractRequest.java:41) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.handleGet(KafkaCruiseControlServlet.java:172) ~[cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGetOrPost(KafkaCruiseControlServlet.java:122) [cruise-control-2.4.23.jar:?]
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGet(KafkaCruiseControlServlet.java:99) [cruise-control-2.4.23.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.servlet-api-3.1.0.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.xeril.util.servlet.ProxyServlet.service(ProxyServlet.java:61) [util-servlet-24.0.66.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at com.linkedin.emweb.ContextBasedHandlerImpl.handle(ContextBasedHandlerImpl.java:73) [emweb-impl-9.2.19.2.jar:?]
        at com.linkedin.emweb.MapBasedHandlerImpl.handle(MapBasedHandlerImpl.java:480) [emweb-impl-9.2.19.2.jar:?]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.Server.handle(Server.java:503) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at com.linkedin.emweb.ThreadPoolWithTracking$QueuedRunnable.run(ThreadPoolWithTracking.java:417) [emweb-impl-9.2.19.2.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
