### ISSUE TITLE
Fatal error during KafkaServer startup at CruiseControlMetricsReporter.getBootstrapServers...

### ISSUE THREAD

**Issue by zornhsu** [linkedin/cruise-control#1430]
when KafkaServer listeners config is omitted. By default listeners config was commented out.

### To reproduce
1. Follow cruise-control quick-start to download Kafka 2.7
2. Append `metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter` to `config/server.properties`
3. `$ cd kafka_2.13-2.7.0 ; bin/kafka-server-start.sh config/server.properties`
Output:
```
...
[2020-12-23 15:30:09,806] INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2020-12-23 15:30:09,823] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.getBootstrapServers(CruiseControlMetricsReporter.java:127)
        at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:139)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:390)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:450)
        at kafka.server.DynamicMetricsReporters.createReporters(DynamicBrokerConfig.scala:794)
        at kafka.server.DynamicMetricsReporters.<init>(DynamicBrokerConfig.scala:743)
        at kafka.server.DynamicBrokerConfig.addReconfigurables(DynamicBrokerConfig.scala:248)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:375)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
        at kafka.Kafka$.main(Kafka.scala:82)
        at kafka.Kafka.main(Kafka.scala)
[2020-12-23 15:30:09,826] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-12-23 15:30:09,827] INFO [SocketServer brokerId=0] Stopping socket server request processors (kafka.network.SocketServer)...```

**Comment by efeg** [comment]
@zornhsu `Kafka 2.7` is not supported, yet. Is this reproducible in supported versions of Kafka?
See https://github.com/linkedin/cruise-control#environment-requirements

**Comment by zornhsu** [comment]
Yes, @efeg. I just tried `kafka_2.12-2.4.0` with `cruise-control-metrics-reporter-2.4.36.jar`. Same error:
```
[2020-12-24 09:26:03,869] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

**Comment by efeg** [comment]
@zornhsu Thanks for reporting the issue -- this is indeed a recently introduced bug.
-- Created a PR to address the issue.
