### ISSUE TITLE
confluent-kafka-2.11-1.0.0-1

### ISSUE THREAD

**Issue by lifehacking** [linkedin/cruise-control#151]
[2018-03-02 19:11:46,818] ERROR Sampling scheduler received Unknown exception when waiting for sampling to finish (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager)
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.fetchSamples(MetricFetcherManager.java:198)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.fetchPartitionMetricSamples(MetricFetcherManager.java:163)
        at com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask.run(SamplingTask.java:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ThreeEarthGod** [comment]
I ask something with this

**Comment by saritago** [comment]
@lifehacking I am seeing same error in logs, is it resolved for you?

**Comment by efeg** [comment]
This issue should be relevant to https://github.com/linkedin/cruise-control/issues/397 -- and has already been fixed.
