### ISSUE TITLE
[Kafka 0.10.2] CruiseControlMetricsReporter cannot be cast to kafka.metrics.KafkaMetricsReporter

### ISSUE THREAD

**Issue by jameskyle** [linkedin/cruise-control#16]
Full stack

    [2017-09-01 21:56:47,140] 0    [main] FATAL kafka.Kafka$  -  java.lang.ClassCastException: 
    com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter cannot be cast to 
    kafka.metrics.KafkaMetricsReporter
	at k 
    kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:65)
	at 
    kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:64)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at kafka.metrics.KafkaMetricsReporter$.startReporters(KafkaMetricsReporter.scala:64)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:27)
	at kafka.Kafka$.main(Kafka.scala:58)
	at kafka.Kafka.main(Kafka.scala)

metrics config:

    kafka.metrics.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

Shared lib location:

    /usr/share/java/kafka/

**Comment by becketqin** [comment]
@jameskyle Please use the config `metric.reporters` instead of `kafka.metrics.reporters`. Also which version of Kafka did you run?

**Comment by jameskyle** [comment]
hey, @becketqin, thanks for the response. This cluster is running: 0.10.2.

**Comment by wangzzu** [comment]
@becketqin It will better if there is an environmental requirement in README.

**Comment by jameskyle** [comment]
With the fix suggested I don't get a startup error. However, I do get this output constantly:

      [2017-09-08 17:33:04,661] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
        [2017-09-08 17:33:34,661] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
        [2017-09-08 17:34:04,661] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
        [2017-09-08 17:34:34,661] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)

At first, the collector was timing out before it could gather a sample. I tried increasing the metric.sampling.interval.ms to as much as 4 hours, but still nada.

**Comment by jameskyle** [comment]
Just to update, I connected to the '__CruiseControlMetrics' topic and read from it, it certainly has metrics stored there. And it's being updated every so often. 

tried to check the offsets for the cruisecontrol consumer group, but it turned up empty.

**Comment by jameskyle** [comment]
And after running for many hours, a restart has this log:

    [2017-09-08 19:56:10,946] INFO Sample loading finished. Loaded 0 partition metrics samples and 0 broker metric samples in 1198 ms (com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore)

**Comment by becketqin** [comment]
@jameskyle What is your message format version configuration? Cruise Control assumes the message format version contains a timestamp. It should be 0.10.0 and above.

**Comment by jameskyle** [comment]
ahhh, that's it. protocol and message formats are 0.8.2 on these.

let me fiddle that.
