### ISSUE TITLE
Problem running cruise control on confluent kafka(java.lang.NoSuchMethodError: 'boolean com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricsUtils.isInterested(com.yammer.metrics.core.MetricName)')

### ISSUE THREAD

**Issue by vipulchandraker** [linkedin/cruise-control#1638]
Hi,

I have placed the cruise-control-metrics-reporter-0.1.0-SNAPSHOT.jar under /usr/share/java/kafka/ location. 

 #ls -l /usr/share/java/kafka/cruise-control-metrics-reporter-0.1.0-SNAPSHOT.jar
-rw-r--r-- 1 root root 51720 Jul 31 17:07 /usr/share/java/kafka/cruise-control-metrics-reporter-0.1.0-SNAPSHOT.jar

I see that the jar is loaded by the broker process as well.
lsof -p 11500 | grep cruise
java    11500 cp-kafka  227r      REG              202,1     51720 17159194 /usr/share/java/kafka/cruise-control-metrics-reporter-0.1.0-SNAPSHOT.jar
java    11500 cp-kafka  367r      REG              202,1     51720  8955089 /usr/share/java/confluent-common/cruise-control-metrics-reporter-0.1.0-SNAPSHOT.jar

I am seeing following exception in broker logs.

`[2021-07-31 17:52:45,621] INFO Kafka startTimeMs: 1627753965621 (org.apache.kafka.common.utils.AppInfoParser)
[2021-07-31 17:52:45,632] INFO App info kafka.admin.client for _confluent-license-admin-1001 unregistered (org.apache.kafka.common.utils.AppInfoParser)
[2021-07-31 17:52:45,634] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics)
[2021-07-31 17:52:45,634] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics)
[2021-07-31 17:52:45,634] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics)
[2021-07-31 17:52:45,635] INFO Trial license for Confluent Enterprise expires in 29 days on 2021-08-30. (io.confluent.license.LicenseManager)
[2021-07-31 17:53:37,451] INFO Cruise Control metrics reporter exited. (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2021-07-31 17:53:37,452] ERROR Uncaught exception in thread 'CruiseControlMetricsReporterRunner': (org.apache.kafka.common.utils.KafkaThread)
java.lang.NoSuchMethodError: 'boolean com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricsUtils.isInterested(com.yammer.metrics.core.MetricName)'
	at com.linkedin.kafka.cruisecontrol.metricsreporter.metric.YammerMetricProcessor.processGauge(YammerMetricProcessor.java:141)
	at com.linkedin.kafka.cruisecontrol.metricsreporter.metric.YammerMetricProcessor.processGauge(YammerMetricProcessor.java:26)
	at com.yammer.metrics.core.Gauge.processWith(Gauge.java:28)
	at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.reportYammerMetrics(CruiseControlMetricsReporter.java:399)
	at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.run(CruiseControlMetricsReporter.java:331)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by tomncooper** [comment]
0.1.0 seems like an strange version number (the latest ones are 2.x.x)? Are you building CC from source? Which branch did you build from (master or one of the migrate branches)?

**Comment by Fattouh92** [comment]
I am facing the exact same issue as well. I am using cp-server 6.0.1 image which is kafka 2.6.0 if I am not mistaken and cruise control 2.5.78. 

My thinking is: confluent has [Self balancing feature](https://docs.confluent.io/platform/current/kafka/sbc/index.html) that builds on top of cruise control. they must include cruise control jars somehow. 
I think there is a clash somehow with the classes included twice. Confluent jars is what gets used and not sure which version or what they do there

@tomncooper can you verify this line of thinking please?
maybe issue https://github.com/linkedin/cruise-control/issues/276 is also related 

@vipulchandraker any updates here?

**Comment by mfouze** [comment]
Hello,
Any update on this case  ?

**Comment by saikumarstkm** [comment]
I am also facing the same error
