### ISSUE TITLE
Malformed \uxxxx encoding

### ISSUE THREAD

**Issue by tooptoop4** [linkedin/cruise-control#1739]
Get this error running via ./kafka-cruise-control-start.sh or
```
/home/user/jdk-13.0.2+8-jre/bin/java -Xmx1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+DisableExplicitGC -Djava.awt.headless=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dkafka.logs.dir=./logs -cp './cruise-control/build/dependant-libs/*:./cruise-control/build/libs/*:./cruise-control-metrics-reporter/build/libs/*' com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain /home/user/cruise-control-2.5.75.jar no.properties
```
even with empty properties file

```
ERROR KafkaCruiseControlMain Uncaught exception on thread Thread[main,5,main]
 java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.base/java.util.Properties.loadConvert(Unknown Source)
        at java.base/java.util.Properties.load0(Unknown Source)
        at java.base/java.util.Properties.load(Unknown Source)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlUtils.readConfig(KafkaCruiseControlUtils.java:836)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:35)
```

**Comment by tooptoop4** [comment]
changing
```
bash -x ./kafka-cruise-control-start.sh /home/user/cruise-control-2.5.76.jar config/cruisecontrol.properties
```
to
```
bash -x ./kafka-cruise-control-start.sh -jars /home/user/cruise-control-2.5.76.jar config/cruisecontrol.properties
```
solved this
