### ISSUE TITLE
ERROR Unsuccessful handshake with session 0x0 (org.apache.zookeeper.server.NettyServerCnxnFactory)

### ISSUE THREAD

**Issue by Cshanmukh80** [linkedin/cruise-control#1741]
2021-11-23 09:18:10,225 INFO Processing ruok command from /127.0.0.1:57924 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-1]
2021-11-23 09:18:10,386 ERROR Unsuccessful handshake with session 0x0 (org.apache.zookeeper.server.NettyServerCnxnFactory) [nioEventLoopGroup-7-2]
2021-11-23 09:18:10,386 WARN Exception caught (org.apache.zookeeper.server.NettyServerCnxnFactory) [nioEventLoopGroup-7-2]
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0000002d00000000000000000000000000003a980000000000000000000000100000000000000000000000000000000000
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0000002d00000000000000000000000000003a980000000000000000000000100000000000000000000000000000000000

**Comment by jlevy8** [comment]
What version of CruiseControl/Kafka/Zookeeper are you running?

Seems like your SSL Configurations are missing.
Have you tried passing the parameters in as suggested in https://github.com/linkedin/cruise-control/issues/1323?

Specifically these JVM System Properties
```-Dzookeeper.client.secure=true \
-Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty \
-Dzookeeper.ssl.keyStore.location=<ks location> \
-Dzookeeper.ssl.keyStore.password=<ks password> \
-Dzookeeper.ssl.trustStore.location=<ts location> \
-Dzookeeper.ssl.trustStore.password=<ts password>

**Comment by Phani2811** [comment]
Hello @jlevy8 - I am also facing same issue. tried setting these JVM parameters as well. it is still failing with same error.

**Comment by Phani2811** [comment]
Hello @Cshanmukh80 - Were you able to fix the issue? if yes, could pls help as am also facing same issue. trying it for few days and stuck completely. any help is much appreciated!

**Comment by romankydybets** [comment]
I am also getting same issue, do anyone resolve it?
