### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by mohitpali** [linkedin/cruise-control#1836]
I have been seeing Unit test failures for the tests that use CCEmbeddedBroker on my Mac.
(MacOS Monetrey v 12.1 - 2.6 GHz 6-Core Intel Core i7)

##### Command to execute test -
``./gradlew build -x integrationTest``

##### Failed Tests are - 

1. AuthenticationIntegrationTest
2. testUnsuccessfulAuthentication
3. TrustedProxySecurityProviderSpnegoFallbackIntegrationTest
4. testUnsuccessfulAuthentication

```
com.linkedin.kafka.cruisecontrol.servlet.security.AuthenticationIntegrationTest > testSuccessfulAuthentication FAILED
    java.lang.IllegalStateException: kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at com.linkedin.kafka.cruisecontrol.metricsreporter.utils.CCEmbeddedBroker.<init>(CCEmbeddedBroker.java:46)
        at com.linkedin.kafka.cruisecontrol.metricsreporter.utils.CCKafkaIntegrationTestHarness.setUp(CCKafkaIntegrationTestHarness.java:34)
        at com.linkedin.kafka.cruisecontrol.CruiseControlIntegrationTestHarness.start(CruiseControlIntegrationTestHarness.java:43)
        at com.linkedin.kafka.cruisecontrol.servlet.security.AuthenticationIntegrationTest.setup(AuthenticationIntegrationTest.java:54)

        Caused by:
        kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
            at app//kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:259)
            at app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
            at app//kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
            at app//kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:255)
            at app//kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:113)
            at app//kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1858)
            at app//kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:375)
            at app//kafka.server.KafkaServer.initZkClient(KafkaServer.scala:399)
            at app//kafka.server.KafkaServer.startup(KafkaServer.scala:207)
            at app//com.linkedin.kafka.cruisecontrol.metricsreporter.utils.CCEmbeddedBroker.startup(CCEmbeddedBroker.java:93)
            at app//com.linkedin.kafka.cruisecontrol.metricsreporter.utils.CCEmbeddedBroker.<init>(CCEmbeddedBroker.java:37)
            ... 3 more 
```

**Comment by mhratson** [comment]
I wasn't able to reproduce it

**Comment by pablopelaezg** [comment]
@mhratson i'm actually seeing the same behavior @mohitpali said. I'm doing a change to support capacity data fetching from AWS MSK, and when I execute this to check if everything is ok:

`./gradlew :cruise-control:test`

All of the integration tests fail due to this:

```
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
            at app//kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:258)
            at app//kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:116)
            at app//kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:2266)
            at app//kafka.zk.KafkaZkClient$.createZkClient(KafkaZkClient.scala:2358)
            at app//kafka.server.KafkaServer.initZkClient(KafkaServer.scala:634)
            at app//kafka.server.KafkaServer.startup(KafkaServer.scala:221)
            at app//com.linkedin.kafka.cruisecontrol.metricsreporter.utils.CCEmbeddedBroker.startup(CCEmbeddedBroker.java:139)
            at app//com.linkedin.kafka.cruisecontrol.metricsreporter.utils.CCEmbeddedBroker.<init>(CCEmbeddedBroker.java:46)
            ... 4 more
 ```
            
Even, I executed the same command with code from `main`, and same result. It's very probable we're missing something while executing any test goal. Checked the docs, and there's no detailed info about testing. Do you know what's happening?

**Comment by pablopelaezg** [comment]
@mhratson found something interesting: Apple Silicon (ARM) based computers have issues starting the Embedded Kafka, and this doesn't happen with x86 based computers. Tested with mine (M1 Laptop) and failed on all Integration tests needing the EmbedKafka, and tested with a `t3.small` EC2 machine and everything run ok.

I ran the `./gradlew :cruise-control:build` command on both M1 Laptop and the EC2 instance, with fresh `main` branches, and these are the outputs for both executions (sorry for the truncated output)

[cruise-control-x86-build-output.log](https://github.com/user-attachments/files/16840634/cruise-control-x86-build-output.log)
[cruise-control-arm-build-output.log](https://github.com/user-attachments/files/16840629/cruise-control-arm-build-output.log)
