### ISSUE TITLE
MSK brokers get random disconnected with Cruise-control attached

### ISSUE THREAD

**Issue by yoyonl** [linkedin/cruise-control#1866]
Hi, 

Currently we are experiencing an issue that as soon we connect Cruise-control to our MSK cluster that random kafka brokers get disconnected for some time and come back(see attached AWS metrics screenshots). As we did not enabled Self healing i'm curious how Cruise-control is influencing our MSK cluster. Unfortunately the logging of both kafka brokers or cruisecontrol is not very clear to me where the problem relies. 

Logs from brokers:
``
[2022-07-17 02:04:17,771] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Partition __consumer_offsets-15 has an older epoch (45) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread)
[2022-07-17 02:04:17,771] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Partition __consumer_offsets-45 has an older epoch (45) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread) | [2022-07-17 02:04:17,771] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Partition __consumer_offsets-45 has an older epoch (45) than the current leader. Will await the new LeaderAndIsr state before resuming fetching. (kafka.server.ReplicaFetcherThread)
[2022-07-17 02:04:17,772] INFO [Log partition=__KafkaCruiseControlPartitionMetricSamples-15, dir=LOG_DIR] Truncating to 5265 has no effect as the largest offset in the log is 5264 (kafka.log.Log)
[2022-07-17 02:04:17,774] INFO Loaded member MemberMetadata(memberId=consumer-amazon.msk.canary.group.broker-3-429-78b5319b-f79f-486a-8585-80a6dfb843fc, groupInstanceId=None, clientId=consumer-amazon.msk.canary.group.broker-3-429, clientHost=/INTERNAL_IP, sessionTimeoutMs=10000, rebalanceTimeoutMs=300000, supportedProtocols=List(range), ) in group amazon.msk.canary.group.broker-3 with generation 5237. (kafka.coordinator.group.GroupMetadata$) | [2022-07-17 02:04:17,774] INFO Loaded member MemberMetadata(memberId=consumer-amazon.msk.canary.group.broker-3-429-78b5319b-f79f-486a-8585-80a6dfb843fc, groupInstanceId=None, clientId=consumer-amazon.msk.canary.group.broker-3-429, clientHost=/INTERNAL_IP, sessionTimeoutMs=10000, rebalanceTimeoutMs=300000, supportedProtocols=List(range), ) in group amazon.msk.canary.group.broker-3 with generation 5237. (kafka.coordinator.group.GroupMetadata$) ``

Logs from cruisecontrol:
``
[2022-07-19 00:34:59,190] INFO [AdminClient clientId=adminclient-2] Node 2 disconnected. (org.apache.kafka.clients.NetworkClient)
 INFO Assign empty capacity to brokers [2] because they are dead and capacity resolver is unable to fetch their capacity. (com.linkedin.kafka.cruisecontrol.monitor.MonitorUtils)
[2022-07-19 01:00:50,070] INFO Finished the precomputation proposal candidates in 6 ms (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:829) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer$ProposalCandidateComputer.run(GoalOptimizer.java:558) ~[cruise-control-0.1.0-SNAPSHOT.jar:?]
at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:388) ~[cruise-control-0.1.0-SNAPSHOT.jar:?]
at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:450) ~[cruise-control-0.1.0-SNAPSHOT.jar:?]
at com.linkedin.kafka.cruisecontrol.analyzer.goals.AbstractGoal.optimize(AbstractGoal.java:130) ~[cruise-control-0.1.0-SNAPSHOT.jar:?]
com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: [RackAwareGoal] Insufficient number of racks to distribute each replica (Current: 2, Needed: 3). Add at least 1 rack with brokers. Add at least 1 rack with brokers.
[2022-07-19 01:00:50,070] WARN Detected unfixable proposal optimization (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)``

Environment:
3x kafka brokers(t3.small)
(MSK)Kafka 2.8.1
CC from migrate_to_kafka_2_5 (2.5.95 on the test time)
Prometheus for scraping(scrape interval 60s)

<img width="646" alt="Screenshot 2022-07-19 at 12 13 47" src="https://user-images.githubusercontent.com/20890102/179727072-647a7556-d76e-4300-92ad-e704844767db.png">
<img width="649" alt="Screenshot 2022-07-19 at 12 13 33" src="https://user-images.githubusercontent.com/20890102/179727091-78f5040e-0aec-4c54-84d0-3e26032c0a8c.png">

**Comment by mohitpali** [comment]
Would you be able to share your Prometheus scraping interval ? Usually JMX metrics become huge to scrape within a short period of time. Try updating the scraping interval to 60 seconds with scraping configuration as ``scrape_interval: 60s``

You would have to update the query at https://github.com/linkedin/cruise-control/blob/4e5927b48bf2581ab76acbbecbf42b355b871b65/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/DefaultPrometheusQuerySupplier.java#L26 
to use 1m to 2m so that you have two datapoints to have irate work.

```
"1 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[2m]))")
```

**Comment by yoyonl** [comment]
> Would you be able to share your Prometheus scraping interval ? Usually JMX metrics become huge to scrape within a short period of time. Try updating the scraping interval to 60 seconds with scraping configuration as `scrape_interval: 60s`
> 
> You would have to update the query at
> 
> https://github.com/linkedin/cruise-control/blob/4e5927b48bf2581ab76acbbecbf42b355b871b65/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/DefaultPrometheusQuerySupplier.java#L26
> 
> 
> to use 1m to 2m so that you have two datapoints to have irate work.
> ```
> "1 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[2m]))")
> ```

Thanks for your reply, i have already set the scraping interval to 60s for prometheus. Regarding the BROKER_CPU_UTIL metric that one looks not available on AWS as Cruise-control is giving a warning in the logs:
``
 WARN Skip generating metric sample for broker 2 because the following required metrics are missing [BROKER_CPU_UTIL]. (com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingUtils)
``

**Comment by yoyonl** [comment]
Found the issue: It was related to memory as the t3.small instances just have 2GB of memory this is to few to work with Cruisecontrol. MSK takes already around the 1,8GB for just operation the cluster.
