### ISSUE TITLE
PrometheusMetricSampler invaild query results

### ISSUE THREAD

**Issue by dude0001** [linkedin/cruise-control#1932]
I have both CC and Prometheus running in Docker containers. I can see Kafka broker, topic and other metrics flowing in Prometheus. CC is able to connect to the Kafka cluster (AWS MSK) and display number of topics, partion, leader skew  etc. I tried to start metrics bootstrap which appears to start successfully. However, I am never seening any of the metrics from Prometheus in CC or metrics being stored in the CC expected topics. I can do a successful wget from the CC container to the promethus/metrics endpoint and see a valid result fetched. Examing the CC logs the only thing I see relevant is the informational message below, no warnings or errorrs related that I've noticed.

`INFO Added 0 metric values. Skipped 4832 invalid query results. (com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.PrometheusMetricSampler)`

It looks like 4,832 query results were fetched but they are invalid in some way such that they cannot be ingested into CC. How can I troubleshoot further to understand why the results are invald?

**Comment by dude0001** [comment]
This was user error. I enabled trace logging by adding to my log4j.properties

```
logger.prometheus.name=com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus
logger.prometheus.level=trace
logger.prometheus.appenderRef.kafkaCruiseControlAppender.ref=kafkaCruiseControlFile
```

This gave me a log entry like

```
TRACE Invalid query result received from Prometheus for query sum by (instance) (kafka_network_RequestMetrics_OneMinuteRate{name="RequestsPerSec",request="FetchConsumer"}) (com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.PrometheusMetricSampler)
com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.InvalidPrometheusResultException: Unexpected host b-2.cluster1.xzmi3f.c3.kafka.us-east-2.amazonaws.com, does not map to any of broker found from Kafka cluster metadata. Brokers found in Kafka cluster metadata = [b-3.p-cluster2.k7attg.c7.kafka.us-east-2.amazonaws.com, b-1.cluster2.k7attg.c7.kafka.us-east-2.amazonaws.com, b-2.cluster2.k7attg.c7.kafka.us-east-2.amazonaws.com]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.PrometheusMetricSampler.getBrokerId(PrometheusMetricSampler.java:262) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.PrometheusMetricSampler.addBrokerMetrics(PrometheusMetricSampler.java:211) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.prometheus.PrometheusMetricSampler.retrieveMetricsForProcessing(PrometheusMetricSampler.java:179) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.AbstractMetricSampler.getSamples(AbstractMetricSampler.java:49) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.fetchSamples(MetricFetcher.java:160) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.fetchMetricsForAssignedPartitions(MetricFetcher.java:129) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.call(MetricFetcher.java:110) ~[cruise-control-2.5.105.jar:?]
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.call(MetricFetcher.java:25) ~[cruise-control-2.5.105.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

The metrics from Prometheus were for a second cluster cluster2 I had originally been testing with, but I now had CC configured for cluster1. I had updated the Prometheus config and rebuilt my Prometheus image with the hard coded cluster2, but docker-compose up was using an old version of the image that was referencing cluster1. Doing a docker-compose build and then docker-compose, both containers started up with the correct configs and worked. Derp.
