### ISSUE TITLE
Getting NotEnoughValidWindowsException when I click on KafkaClusterLoad or any similar tabs

### ISSUE THREAD

**Issue by aagrrawal** [linkedin/cruise-control#2085]
Getting below Exception when I click on KafkaClusterLoad or any similar tabs. I am using kafka v3.3.1 and cruise-control v2.5.132. Went through discussion in #310 but it didn't help. I have manually created __CruiseControlMetrics topic in kafka cluster. Pl help

```
Caused by: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There is no window available in range [-1, 1701684649907] (index [1, -1]). Window index (current: 0, oldest: 0).
	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.aggregate(MetricSampleAggregator.java:202) ~[cruise-control-core-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.aggregate(KafkaPartitionMetricSampleAggregator.java:151) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:503) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.clusterModel(KafkaCruiseControl.java:370) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.clusterModel(LoadRunnable.java:111) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.clusterModelFromEarliest(LoadRunnable.java:93) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.getResult(LoadRunnable.java:76) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.getResult(LoadRunnable.java:26) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.run(LoadRunnable.java:26) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
```

**Comment by aagrrawal** [comment]
@efeg could you pls have a look ?

**Comment by aagrrawal** [comment]
It seems to me that probably kafka is not able to write to __CruiseControlMetrics topic  as this was empty -> 
% kafka-console-consumer.sh --topic __CruiseControlMetrics --from-beginning --bootstrap-server localhost:9092

Are kafka v3.3.1 and cruise-control v2.5.132 compatible ?

**Comment by aagrrawal** [comment]
Hi @mhratson, I checked CC logs, I didn't get any error after __CruiseControlMetrics was created. I got error NotEnoughValidWindowsException when I clicked KafkaClusterLoad tab on cruise control ui.

**Comment by aagrrawal** [comment]
How is metric written to __CruiseControlMetrics topic ? Saw this in CC log during CC startup - "Collected 0 partition metric samples for 0 partitions." Is it normal ? 

```
[2023-12-04 21:55:56,568] INFO [Consumer clientId=CruiseControlMetricsReporterSampler-consumer--6371283249548768098, groupId=null] Resetting the last seen epoch of partition __CruiseControlMetrics-0 to 3 since the associated topicId changed from null to gq4rghsKQ7ivpr82jkpJeg (org.apache.kafka.clients.Metadata)
[2023-12-04 21:55:56,574] INFO [Consumer clientId=CruiseControlMetricsReporterSampler-consumer--6371283249548768098, groupId=null] Seeking to offset 0 for partition __CruiseControlMetrics-0 (org.apache.kafka.clients.consumer.KafkaConsumer)
[2023-12-04 21:56:01,578] INFO Finished sampling from topic __CruiseControlMetrics for partitions [0] in time range [1701706916549,1701707156554]. Collected 0 metrics. (com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler)
[2023-12-04 21:56:01,579] INFO Collected 0 partition metric samples for 0 partitions. Total partition assigned: 116. (com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingFetcher)
[2023-12-04 21:56:01,579] INFO Collected 0 broker metric samples for 0 brokers. (com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingFetcher)
[2023-12-04 21:56:01,583] INFO Finished sampling in 5026 ms. (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager)

```

**Comment by aagrrawal** [comment]
I am starting cruise control like this - `./kafka-cruise-control-start.sh config/cruisecontrol.properties`

**Comment by mhratson** [comment]
@aagrrawal we need to ensure metrics is produced into `__CruiseControlMetrics`. So worth checking kafka logs if there are any related errors…

**Comment by marcelloromani** [comment]
I am facing the same issue.
I left Cruise Control running overnight, so lack of metrics shouldn't be a problem.

I have read somewhere that the error might be caused by a mismatch in the message format version.

I found this line in the readme file:

https://github.com/linkedin/cruise-control/blob/fa21067d968eff7aba06358642c7aeb85e7a9836/README.md?plain=1#L58

> `message.format.version` `0.10.0` and above is needed.

I believe in my case this could be the reason:
I initially installed Cruise Control 2.5.36
Later I replaced my installation with Cruise Control 2.5.99

My hypothesis is this: I creatd the  ` __CruiseControlMetric` topic for the first CC install, 2.5.36, which started populating it with messages with a message format < 0.10.0
I then upgraded to CC 2.5.99, which now finds messages in an old format.

**Comment by tedherring-smarsh** [comment]
Any updates here I'm seeing the same issue?  I see my  `__CruiseControlMetrics` appears empty, but I can write to that topic via console-producer.  I can also write to my own `my-topic`

**Comment by CCisGG** [comment]
> Any updates here? I'm seeing the same issue. I see my __CruiseControlMetrics appears empty, but I can write to that topic via console-producer. I can also write to my own my-topic

@tedherring-smarsh 
In that case I think your CC+Kafka may not setup correctly. To make CC produce metrics to that topic, you need to inject the CruiseControlMetricsReporter in to your Kafka broker. Follow the README: Quick Start section 1.

**Comment by 1299618103** [comment]
> 当我单击 KafkaClusterLoad 或任何类似选项卡时，出现以下异常。我正在使用 kafka v3.3.1 和 Cruise-control v2.5.132。[在#310](https://github.com/linkedin/cruise-control/issues/310)中进行了讨论，但没有帮助。我已在 kafka 集群中手动创建了 __CruiseControlMetrics 主题。请帮忙
> 
> ```
> Caused by: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There is no window available in range [-1, 1701684649907] (index [1, -1]). Window index (current: 0, oldest: 0).
> 	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.aggregate(MetricSampleAggregator.java:202) ~[cruise-control-core-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.aggregate(KafkaPartitionMetricSampleAggregator.java:151) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:503) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.clusterModel(KafkaCruiseControl.java:370) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.clusterModel(LoadRunnable.java:111) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.clusterModelFromEarliest(LoadRunnable.java:93) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.getResult(LoadRunnable.java:76) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.getResult(LoadRunnable.java:26) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.LoadRunnable.run(LoadRunnable.java:26) ~[cruise-control-2.5.132-SNAPSHOT.jar:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
> ```

I had the same problem. Did you solve it？

**Comment by marcelloromani** [comment]
> To make CC produce metrics to that topic, you need to inject the CruiseControlMetricsReporter in to your Kafka broker.

How can that be done when using managed kafka serivces like Amazon MSK?

**Comment by CCisGG** [comment]
> I had the same problem. Did you solve it？

@1299618103 did you follow the README to setup CruiseControlMetricsReporter in your Kafka cluster?

**Comment by CCisGG** [comment]
> How can that be done when using managed kafka serivces like Amazon MSK?

@marcelloromani  Please feel free to reach out to Amazon MSK support. I guess there could be some ENV setup you can use in your MSK portal, but I personally didn't use it before so not exactly sure how they made it pass through those configs.

**Comment by CCisGG** [comment]
@mhratson This is a popular issue so I'd like to invite you to the discussion.

**Comment by 1299618103** [comment]
> > 我有同样的问题。你解决了吗？
> 
> @1299618103您是否按照自述文件在 Kafka 集群中设置 CruiseControlMetricsReporter ？

I set it, my other clusters are normal, this cluster is abnormal after expansion，the details are here  #2107

**Comment by marcelloromani** [comment]
> > How can that be done when using managed kafka serivces like Amazon MSK?
> 
> @marcelloromani Please feel free to reach out to Amazon MSK support. I guess there could be some ENV setup you can use in your MSK portal, but I personally didn't use it before so not exactly sure how they made it pass through those configs.

https://docs.aws.amazon.com/msk/latest/developerguide/cruise-control.html

As far as I could see, for MSK we need to provision a Prometheus instance that scrapes the OpenTelemetry MSK endpoints, and point Cruise Control to this Prometheus instance to read the MSK metrics it needs.
