### ISSUE TITLE
POST request '/rebalance'   have a error：NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range 

### ISSUE THREAD

**Issue by 1299618103** [linkedin/cruise-control#2107]
I have a problem，version:cruise-control:2.5.16，Deployed on K8s，kafka version:2.5.1
![image](https://github.com/linkedin/cruise-control/assets/123084338/e55114e5-f443-4232-8230-1c5c896f897d)

**Encountered when performing rebalancing：**
ERROR: Error processing POST request '/rebalance' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034225740] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)'.

**error log:**
java.util.concurrent.ExecutionException: Operation 'Rebalance' received exception. com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034795731] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationFuture.get(OperationFuture.java:49)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager$UserTaskInfo.logOperation(UserTaskManager.java:745)
	at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager.lambda$checkActiveUserTasks$1(UserTaskManager.java:348)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034795731] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:160)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.workWithoutClusterModel(RebalanceRunnable.java:113)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:166)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.getResult(RebalanceRunnable.java:86)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.getResult(RebalanceRunnable.java:30)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.run(GoalBasedOperationRunnable.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 more
Caused by: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034795731] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)
	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.validateCompleteness(MetricSampleAggregator.java:541)
	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.aggregate(MetricSampleAggregator.java:213)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.aggregate(KafkaPartitionMetricSampleAggregator.java:151)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:541)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.clusterModel(KafkaCruiseControl.java:335)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.ProposalsRunnable.workWithClusterModel(ProposalsRunnable.java:87)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:154)
	... 11 more
162046190 [mizerExecutor-0] INFO  control.analyzer.GoalOptimizer  - Skipping proposal precomputing because load monitor does not have enough snapshots.
162063174 [qtp577442875-54] INFO  ler.async.AbstractAsyncRequest  - Processing async request RebalanceRequest.
162063175 [qtp577442875-54] INFO  ontrol.servlet.UserTaskManager  - Fetch an existing UserTask 781355f6-edf5-4e54-8f69-47336a842644
162063177 [qtp577442875-54] ERROR vlet.KafkaCruiseControlServlet  - Error processing POST request '/rebalance' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034795731] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)'.
java.util.concurrent.ExecutionException: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034795731] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.AbstractAsyncRequest.getResponse(AbstractAsyncRequest.java:57)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.AbstractRequest.handle(AbstractRequest.java:40)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.handlePost(KafkaCruiseControlServlet.java:217)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGetOrPost(KafkaCruiseControlServlet.java:125)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doPost(KafkaCruiseControlServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1705034795731] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=7568, granularity=ENTITY)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:160)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.workWithoutClusterModel(RebalanceRunnable.java:113)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:166)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.getResult(RebalanceRunnable.java:86)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.getResult(RebalanceRunnable.java:30)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.OperationRunnable.run(OperationRunnable.java:45)
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.run(GoalBasedOperationRunnable.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

**Checked the status：**
![image](https://github.com/linkedin/cruise-control/assets/123084338/51420cb7-c746-4054-b2ed-14eee962eae2)

**There's always been a log like this:**
[omalyDetector-6] WARN  detector.GoalViolationDetector  - Skipping goal violation detection for DiskCapacityGoal because load completeness requirement is not met.
161655490 [omalyDetector-6] WARN  detector.GoalViolationDetector  - Skipping goal violation detection for NetworkInboundCapacityGoal because load completeness requirement is not met.
161655501 [omalyDetector-6] WARN  detector.GoalViolationDetector  - Skipping goal violation detection for NetworkOutboundCapacityGoal because load completeness requirement is not met.
161655509 [omalyDetector-6] WARN  detector.GoalViolationDetector  - Skipping goal violation detection for CpuCapacityGoal because load completeness requirement is not met.
161655689 [mizerExecutor-0] INFO  control.analyzer.GoalOptimizer  - Skipping proposal precomputing because load monitor does not have enough snapshots.
161685702 [mizerExecutor-0] INFO  control.analyzer.GoalOptimizer  - Skipping proposal precomputing because load monitor does not have enough snapshots.
161715744 [mizerExecutor-0] INFO  control.analyzer.GoalOptimizer  - Skipping proposal precomputing because load monitor does not have enough snapshots.
161745805 [mizerExecutor-0] INFO  control.analyzer.GoalOptimizer  - Skipping proposal precomputing because load monitor does not have enough snapshots.
161771906 [lingScheduler-1] INFO  .sampling.MetricFetcherManager  - Kicking off metric sampling for time range [1705034433440, 1705034553440], duration 120000 ms with timeout 120000 ms.
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 2720602229 for partition __CruiseControlMetrics-11
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1730427153 for partition __CruiseControlMetrics-10
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1160867028 for partition __CruiseControlMetrics-9
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 4737896776 for partition __CruiseControlMetrics-8
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1278776998 for partition __CruiseControlMetrics-7
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 2751284920 for partition __CruiseControlMetrics-6
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1192141388 for partition __CruiseControlMetrics-5
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1115875043 for partition __CruiseControlMetrics-4
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 3912479386 for partition __CruiseControlMetrics-3
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1204510468 for partition __CruiseControlMetrics-2
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 2919130678 for partition __CruiseControlMetrics-1
161771915 [MetricFetcher-0] INFO  clients.consumer.KafkaConsumer  - [Consumer clientId=CruiseControlMetricsReporterSampler-consumer-2172841471367763004, groupId=null] Seeking to offset 1212795408 for partition __CruiseControlMetrics-0
161772325 [MetricFetcher-0] INFO  eControlMetricsReporterSampler  - Finished sampling for topic partitions [__CruiseControlMetrics-11, __CruiseControlMetrics-10, __CruiseControlMetrics-9, __CruiseControlMetrics-8, __CruiseControlMetrics-7, __CruiseControlMetrics-6, __CruiseControlMetrics-5, __CruiseControlMetrics-4, __CruiseControlMetrics-3, __CruiseControlMetrics-2, __CruiseControlMetrics-1, __CruiseControlMetrics-0] in time range [1705034433440,1705034553440]. Collected 120320 metrics.
161772395 [MetricFetcher-0] WARN  tor.sampling.holder.BrokerLoad  - Broker 9 is missing 5/488 topics metrics and 6/540 leader partition metrics. Missing leader topics: [source-tidb-xdf-scrm-cluster-scrm-xcrm_wework_qos_analysis_003, source-mysql-JWAPI-api-vip_application, source-mysql-164996-sac_mgmt-biz_classroom, source-tidb-xdf-scrm-cluster-scrm-xcrm_clue_extend_001, source-tidb-xdf-k12-cluster-xdf_wechat-qw_fetch_task].
161772395 [MetricFetcher-0] WARN  tor.sampling.holder.BrokerLoad  - Broker 10 is missing 9/803 topics metrics and 10/1005 leader partition metrics. Missing leader topics: [source-tidb-xdf-aick-cluster-n_pad-pad_ai_question_answer, source-tidb-81126-xdf_order-oc_bm_order_item, source-mysql-115126-opt_ms-opt_ms_instance, source-mysql-TiDB_MySQL_ZB_04-xdf_order-oc_vip_order_item, source-mysql-JWAPI-api-bs_lesson, source-mysql-JWAPI-api-bs_class, source-mysql-SCRM-BigData-workflow-detention_retain_sheet, source-mysql-JWAPI-api-vip_application_detail, source-tidb-xdf-k12-cluster-xdf_wechat-qw_group_send_record_detail].
161772400 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-176804-word_fast_prod-word_page_event and partition 1.
161772404 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-42933-classcenter-CAMERA_CHECK_RECORD and partition 2.
161772405 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-176804-word_fast_prod-word_today_task and partition 1.
161772407 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-aliyun-bigdata-cluster-newmedia_data-c_center_student and partition 2.
161772407 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-aliyun-bigdata-cluster-newmedia_data-c_center_student and partition 1.
161772408 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-xdf-scrm-cluster-scrm-xcrm_clue_004 and partition 0.
161772408 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-xdf-k12-cluster-xdf_wechat-qw_msg_file and partition 1.
161772409 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-51063-gezi-gz_course and partition 1.
161772410 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-99498-91sys-CRM_RPT_TMK_RESOURCE and partition 1.
161772413 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-mysql-116965-xdfcall-opencc_union_cdr and partition 0.
161772415 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-xdf-k12-cluster-xdf_wechat-qw_group_chat_msg and partition 0.
161772415 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-xdf-scrm-cluster-scrm-xcrm_schedule and partition 1.
161772417 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic __CruiseControlMetrics and partition 8.
161772418 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-xdf-k12-cluster-xdf_wechat-qw_rule_group_range and partition 1.
161772418 [MetricFetcher-0] ERROR tor.sampling.holder.BrokerLoad  - Partition metric PARTITION_SIZE does not exist for dot handled topic source-tidb-xdf-k12-cluster-xdf_wechat-qw_rule_group_range and partition 2.
161772419 [MetricFetcher-0] WARN  monitor.sampling.SamplingUtils  - Skip generating metric sample for broker 9 because there are not enough topic metrics to generate broker metrics.
161772420 [MetricFetcher-0] WARN  monitor.sampling.SamplingUtils  - Skip generating metric sample for broker 10 because there are not enough topic metrics to generate broker metrics.
161772420 [MetricFetcher-0] INFO  .CruiseControlMetricsProcessor  - Generated 7525(43 skipped by broker {6=7, 7=4, 8=4, 9=8, 10=13, 11=7}) partition metric samples and 10(2 skipped) broker metric samples for timestamp 1705034550684.
161772494 [MetricFetcher-0] INFO  nitor.sampling.SamplingFetcher  - Collected 7525 partition metric samples for 7525 partitions. Total partition assigned: 7568.
161772494 [MetricFetcher-0] INFO  nitor.sampling.SamplingFetcher  - Collected 10 broker metric samples for 10 brokers.
161772687 [lingScheduler-1] INFO  .sampling.MetricFetcherManager  - Finished sampling in 778 ms.

**Comment by mhratson** [comment]
see https://github.com/linkedin/cruise-control/issues/1327#issuecomment-695088894 for details.

**Comment by 1299618103** [comment]
> see [#1327 (comment)](https://github.com/linkedin/cruise-control/issues/1327#issuecomment-695088894) for details.
I think there is a problem on the broker side, but I have not found the specific reason. It occurs after the cluster expansion. The log of the broker side shows that: KafkaYammerMetrics not found. Metrics will be used. (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter). 
When a normal cluster starts, the following information is displayed: **KafkaYammerMetrics found and will be used. (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)**

**Here are some warning messages:**
 Got error produce response with correlation id 69699 on topic-partition __CruiseControlMetrics-11, retrying (4 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,212] WARN [Producer clientId=CruiseControlMetricsReporter] Received invalid metadata error in produce request on partition __CruiseControlMetrics-11 due to org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,212] WARN [Producer clientId=CruiseControlMetricsReporter] Got error produce response with correlation id 69699 on topic-partition __CruiseControlMetrics-10, retrying (4 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,212] WARN [Producer clientId=CruiseControlMetricsReporter] Received invalid metadata error in produce request on partition __CruiseControlMetrics-10 due to org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Got error produce response with correlation id 69699 on topic-partition __CruiseControlMetrics-9, retrying (4 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Received invalid metadata error in produce request on partition __CruiseControlMetrics-9 due to org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Got error produce response with correlation id 69699 on topic-partition __CruiseControlMetrics-6, retrying (4 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Received invalid metadata error in produce request on partition __CruiseControlMetrics-6 due to org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Got error produce response with correlation id 69699 on topic-partition __CruiseControlMetrics-5, retrying (4 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Received invalid metadata error in produce request on partition __CruiseControlMetrics-5 due to org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2024-01-15 06:01:13,213] WARN [Producer clientId=CruiseControlMetricsReporter] Got error produce response with correlation id 69699 on topic-partition __CruiseControlMetrics-4, retrying (4 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)

and

WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_BYTES_OUT,time=1700539243529,brokerId=1,topic=source-mysql-51022-popteachdata-paper_user_sg_paper_stat,value=1.078] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_PRODUCE_REQUEST_RATE,time=1700539243529,brokerId=1,topic=source-mysql-165441-gn_item-pe_info_flow_qa,value=0.038] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_FETCH_REQUEST_RATE,time=1700539243529,brokerId=1,topic=source-tidb-xdf-scrm-cluster-scrm-crm_bj_cc_cdr,value=0.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_FETCH_REQUEST_RATE,time=1700539243529,brokerId=1,topic=source-mysql-115219-group_on-t_market_user_visit,value=136.325] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_FETCH_REQUEST_RATE,time=1700539243529,brokerId=1,topic=source-mysql-jiketong-skynet-wechat_contact,value=0.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_PRODUCE_REQUEST_RATE,time=1700539243529,brokerId=1,topic=source-mysql-TiDB_MySQL_ZB_04-xdf_order-oc_bm_preferential,value=0.272] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_BYTES_OUT,time=1700539243529,brokerId=1,topic=source-tidb-xdf-oa-cluster-workflow_engine-e_flow_versions,value=0.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_FETCH_REQUEST_RATE,time=1700539243529,brokerId=1,topic=source-mysql-postgraduate_examination-db_omo_course-pe_exam_score,value=0.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_MESSAGES_IN_PER_SEC,time=1700539243529,brokerId=1,topic=source-mysql-115219-group_on-t_market_user_visit,value=0.023] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2023-11-21 12:00:57,336] WARN Failed to send Cruise Control metric [TOPIC_METRIC,TOPIC_BYTES_IN,time=1700539243529,brokerId=1,topic=source-mysql-44579-exam-t_course_info_class,value=0.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)

**Comment by CCisGG** [comment]
> WARN Failed to send Cruise Control metric

I'm assuming this is the log on your kafka host? I think this is likely to be cause of your problem. If CC fails to send the metric to the _CruiseControlMetrics topic, CC will not be able to build valid windows. You may need to further investigate the root cause of this warning log.
