### ISSUE TITLE
Failed to describe Kafka cluster configs when using KafkaAdminTopicConfigProvider

### ISSUE THREAD

**Issue by marcelloromani** [linkedin/cruise-control#2153]
I am deploying CC 2.5.137 on EKS, and trying to connect it to MSK

Following the "run without zookeeper" instructions, I am using the kafka admin topic config provider (instead of the non-admin one used in the zookeper setup).

Cruise Control fails during startup with this exception:
```
13:49:28.985 [main] ERROR com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain -- Uncaught exception on thread Thread[main,5,main]
java.lang.RuntimeException: Failed to describe Kafka cluster configs.
        at com.linkedin.kafka.cruisecontrol.config.KafkaAdminTopicConfigProvider.configure(KafkaAdminTopicConfigProvider.java:174)
        at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfigUtils.getConfiguredInstance(KafkaCruiseControlConfigUtils.java:49)
        at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:98)
        at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:156)
        at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:125)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:126)
        at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:34)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlApp.<init>(KafkaCruiseControlApp.java:36)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlServletApp.<init>(KafkaCruiseControlServletApp.java:32)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlUtils.getCruiseControlApp(KafkaCruiseControlUtils.java:926)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:37)
```

I have been trying to debug this issue for quite some time, especially checking the IAM policies, to no avail.

**Comment by sappusaketh** [comment]
can you share your properties file I m using against MSK with IAM auth its working fine I m also using without zookeeper config

**Comment by sappusaketh** [comment]
config looks fine to me have you verified that your cruise-control node/pod was able to resolve your MSK dns?

**Comment by marcelloromani** [comment]
These are the MSK-related permissions attached to the IAM role:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"kafka:RebootBroker",
				"kafka:ListScramSecrets",
				"kafka:ListNodes",
				"kafka:ListKafkaVersions",
				"kafka:ListConfigurations",
				"kafka:ListConfigurationRevisions",
				"kafka:GetBootstrapBrokers",
				"kafka:DescribeConfiguration",
				"kafka:DescribeCluster",
				"kafka-cluster:WriteDataIdempotently",
				"kafka-cluster:DescribeCluster",
				"kafka-cluster:Connect",
				"kafka-cluster:AlterCluster"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:kafka:*:<aws_account>:cluster/<msk_cluster_name>/<msk_cluster_id>",
			"Sid": "AllowMskAccessCluster"
		},
		{
			"Action": [
				"kafka-cluster:WriteData",
				"kafka-cluster:ReadData",
				"kafka-cluster:DescribeTransactionalId",
				"kafka-cluster:DescribeTopicDynamicConfiguration",
				"kafka-cluster:DescribeTopic",
				"kafka-cluster:DeleteTopic",
				"kafka-cluster:CreateTopic",
				"kafka-cluster:AlterTransactionalId",
				"kafka-cluster:AlterTopicDynamicConfiguration",
				"kafka-cluster:AlterTopic"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:kafka:*:<aws_account>:topic/<msk_cluster_name>/<msk_cluster_id>/*",
				"arn:aws:kafka:*:<aws_account>:topic/<msk_cluster_name>/*"
			],
			"Sid": "AllowMskAccessTopic"
		},
		{
			"Action": [
				"kafka-cluster:DescribeGroup",
				"kafka-cluster:DeleteGroup",
				"kafka-cluster:AlterGroup"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:kafka:*:<aws_account>:group/<msk_cluster_name>/<msk_cluster_id>/*",
			"Sid": "AllowMskAccessGroup"
		}
	]
}{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"kafka:RebootBroker",
				"kafka:ListScramSecrets",
				"kafka:ListNodes",
				"kafka:ListKafkaVersions",
				"kafka:ListConfigurations",
				"kafka:ListConfigurationRevisions",
				"kafka:GetBootstrapBrokers",
				"kafka:DescribeConfiguration",
				"kafka:DescribeCluster",
				"kafka-cluster:WriteDataIdempotently",
				"kafka-cluster:DescribeCluster",
				"kafka-cluster:Connect",
				"kafka-cluster:AlterCluster"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:kafka:*:<aws_account>:cluster/<msk_cluster_name>/<msk_cluster_id>",
			"Sid": "AllowMskAccessCluster"
		},
		{
			"Action": [
				"kafka-cluster:WriteData",
				"kafka-cluster:ReadData",
				"kafka-cluster:DescribeTransactionalId",
				"kafka-cluster:DescribeTopicDynamicConfiguration",
				"kafka-cluster:DescribeTopic",
				"kafka-cluster:DeleteTopic",
				"kafka-cluster:CreateTopic",
				"kafka-cluster:AlterTransactionalId",
				"kafka-cluster:AlterTopicDynamicConfiguration",
				"kafka-cluster:AlterTopic"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:kafka:*:<aws_account>:topic/<msk_cluster_name>/<msk_cluster_id>/*",
				"arn:aws:kafka:*:<aws_account>:topic/<msk_cluster_name>/*"
			],
			"Sid": "AllowMskAccessTopic"
		},
		{
			"Action": [
				"kafka-cluster:DescribeGroup",
				"kafka-cluster:DeleteGroup",
				"kafka-cluster:AlterGroup"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:kafka:*:<aws_account>:group/<msk_cluster_name>/<msk_cluster_id>/*",
			"Sid": "AllowMskAccessGroup"
		}
	]
}
```

**Comment by marcelloromani** [comment]
Also in the Cruise Control pod logs I see:
```
18:52:59.443 [main] INFO org.apache.kafka.common.security.authenticator.AbstractLogin -- Successfully logged in.
```
```
18:52:59.968 [main] INFO org.apache.kafka.common.utils.AppInfoParser -- Kafka version: 3.6.1
```
The MSK cluster is running Kafka 2.8.1
Maybe this Kafka version mismatch is causing issues?

**Comment by marcelloromani** [comment]
Related issues/docs:
https://github.com/linkedin/cruise-control/issues/1415
https://github.com/linkedin/cruise-control/wiki/Run-without-ZooKeeper

**Comment by marcelloromani** [comment]
Thanks for confirming.

**Comment by pascaruchan** [comment]
Hello, it may be a little too late, but I encountered the same issue as @marcelloromani 
The solution that I found was to add the missing IAM action: `kafka-cluster:DescribeClusterDynamicConfiguration` and Cruise Control started successfully!

I'm using: `Kafka 3.8.x` / `CC 2.5.147` (current main branch i guess e30eaf352c31511241f4dfae457fbcb77022a9c6)
