### ISSUE TITLE
Error processing POST request `/add_broker` due to: 'null'

### ISSUE THREAD

**Issue by ynasser** [linkedin/cruise-control#218]
Hello! First, thank you for building and maintaining such an awesome tool :)

I'm running into a similar issue to #214. When I try to add a new broker via:
```
curl -X POST -c .cruise_control_cookies/ http://localhost:9090/kafkacruisecontrol/add_broker?dryrun=true
```

I get `Error processing POST request '/add_broker' due to: 'null'` and the app prints these error logs:
```
[2018-05-04 17:12:56,880] INFO Received Request%28POST+%2F%2Flocalhost%3A9090%2Fkafkacruisecontrol%2Fadd_broker%3Fdryrun%3Dtrue%29%40657b3089, http%3A%2F%2Flocalhost%3A9090%2Fkafkacruisecontrol%2Fadd_broker from 127.0.0.1 (CruiseControlPublicAccessLogger)
[2018-05-04 17:12:56,881] ERROR Error processing POST request '/add_broker' due to: 'null'. (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)
java.lang.NullPointerException
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.setErrorResponse(KafkaCruiseControlServlet.java:551)
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.addOrRemoveBroker(KafkaCruiseControlServlet.java:1079)
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doPost(KafkaCruiseControlServlet.java:443)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:748)

```

Unlike #214 though:
- I'm able to execute `curl --get http://localhost:9090/kafkacruisecontrol/load` just fine with no `NullPointerExceptions`.
- I haven't removed `brokerId: -1` from `config/capacity.json`, but I did update it to have the following values:

```
{
  "brokerCapacities":[
    {
      "brokerId": "-1",
      "capacity": {
        "DISK": "1600000",
        "CPU": "100",
        "NW_IN": "10000",
        "NW_OUT": "64000"
      },
      "doc": "This is the default capacity. Capacity unit used for disk is in MB, cpu is in percentage, network throughput is in KB."
    },
    {
      "brokerId": "0",
      "capacity": {
        "DISK": "500000",
        "CPU": "100",
        "NW_IN": "50000",
        "NW_OUT": "50000"
      },
      "doc": "This overrides the capacity for broker 0."
    }
  ]
}
```

Most recent commit hash I have from upstream master is: `dd6481550b18531af968c17d64ff880e0625599c`.

Any advice on how to deal with this would be appreciated.

**Comment by ynasser** [comment]
Hm, I'll try bumping to most recent master and try again, since there seems to have been some changes in the last few days to deal with something similar to this.

**Comment by ynasser** [comment]
Alas, even after rebasing onto `c2791d967557a54a762fbbd3d8fdb56f6e8fcfb9`, still no luck :(

**Comment by becketqin** [comment]
@ynasser Thanks for reporting the issue. It looks the problem is the error message itself was null. This is an error in our servlet code. It doesn't seem to be related to any configuration issue. I will put a patch shortly.

**Comment by ynasser** [comment]
Thanks so much @becketqin.
