### ISSUE TITLE
Kafka cluster always has under replicated partitions after CC rebalance

### ISSUE THREAD

**Issue by ynasser** [linkedin/cruise-control#231]
Hi, not sure if this is directly a CC issue, but just want to flag it in case others are running into such behaviour.

We've been trying out CC on a test Kafka cluster, and after almost every rebalance we've executed with CC, the cluster has been left in a state with a large number of under replicated partitions (and sometimes hanging ongoing reassignments that last >24 hours).

After investigating some thread dumps with `jstack`, it seems that this [Kafka `ReplicaFetcherThread`  issue](https://issues.apache.org/jira/browse/KAFKA-6649) is the underlying recurring problem.

We’ve conducted several tests now, and this is only occurring as a result of CC rebalances, and is not a problem with our normal tools.

We’re continuing to investigate, and will update this thread if we find anything.

**Comment by efeg** [comment]
Hi @ynasser ,
The time it takes to rebalance the cluster depends on the 1) network capacity between brokers, 2) the existing nw in/out traffic to/from brokers, and 3) the value of `num.concurrent.partition.movements.per.broker` config in `cruisecontrol.properties`. Once the throttling support for the inter-broker data transfer rate as described in https://github.com/linkedin/cruise-control/issues/150 is added, it will also impact the rebalance time.

Currently due to the way the rebalance works, it is expected to see URPs in the cluster during rebalance. However, once the rebalance is done, i.e. the CC executor state shows no task in progress, we should not see any URPs.

Do you observe URPs during or after the rebalance?

**Comment by ynasser** [comment]
Hi @efeg, thanks for your response.

We know that rebalances take time, and that URPs are normal while they are undergoing. In this case, we are seeing them stick around **after** both (1) CC says that there's no task in progress, and (2) kafka manager says the rebalance is complete.

In some test cases, the URPs have been observed to stick around for >4 days after a CC-initiated rebalance, until we fix the state of the Kafka cluster manually. These URPs are the result of the `ReplicaFetcherThread` bug linked above, and we've only observed these errors after using CC.

**Comment by jeremydonahue** [comment]
Hi @efeg, I wanted to report that I'm also experiencing this problem. And like @ynasser said, it has thus far only occurred when using Cruise Control. Unfortunately we won't be able to use CC in production until this issue is resolved. 

Cruise Control version: a1dc8d72
Kafka version: 1.0.1-cp1

Here's the Kafka exception from my logs  (note the partition _test2-0_ in both outputs):
```
2018-06-22T16:09:05.355-07:00 [ReplicaFetcher replicaId=4, leaderId=1, fetcherId=1] Error due to
2018-06-22T16:09:05.356212198-07:00 kafka.common.KafkaException: Error processing data for partition test2-0 offset 1
2018-06-22T16:09:05.356301346-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(AbstractFetcherThread.scala:204)
2018-06-22T16:09:05.356322689-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(AbstractFetcherThread.scala:172)
2018-06-22T16:09:05.356336218-07:00     at scala.Option.foreach(Option.scala:257)
2018-06-22T16:09:05.356348214-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2$$anonfun$apply$mcV$sp$1.apply(AbstractFetcherThread.scala:172)
2018-06-22T16:09:05.356364261-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2$$anonfun$apply$mcV$sp$1.apply(AbstractFetcherThread.scala:169)
2018-06-22T16:09:05.356377091-07:00     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
2018-06-22T16:09:05.356389263-07:00     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
2018-06-22T16:09:05.356403018-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2.apply$mcV$sp(AbstractFetcherThread.scala:169)
2018-06-22T16:09:05.356434945-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2.apply(AbstractFetcherThread.scala:169)
2018-06-22T16:09:05.356453102-07:00     at kafka.server.AbstractFetcherThread$$anonfun$processFetchRequest$2.apply(AbstractFetcherThread.scala:169)
2018-06-22T16:09:05.356465785-07:00     at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:217)
2018-06-22T16:09:05.356480589-07:00     at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:167)
2018-06-22T16:09:05.356493187-07:00     at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
2018-06-22T16:09:05.356505643-07:00     at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)
2018-06-22T16:09:05.356537197-07:00 Caused by: org.apache.kafka.common.errors.OffsetOutOfRangeException: Cannot increment the log start offset to 1 of partition test2-0 since it is larger than the high watermark -1
```

And the associated task output from Cruise Control:
```
[2018-06-22 16:09:14,460] INFO Completed tasks: [{EXE_ID: 193, REPLICA_ACTION, {unified-logs-key-test-0, oldLeader: 5, [5, 3, 4] -> [5, 1, 4]}, COMPLETED}, {EXE_ID: 194, REPLICA_ACTION, {test2-0, oldLeader: 2, [2, 3, 4] -> [1, 3, 4]}, COMPLETED}, {EXE_ID: 196, REPLICA_ACTION, {unified-logs-6, oldLeader: 3, [3, 2, 4] -> [3, 1, 4]}, COMPLETED}, {EXE_ID: 197, REPLICA_ACTION, {__CruiseControlMetrics-1, oldLeader: 2, [2, 3, 4] -> [1, 3, 4]}, COMPLETED}, {EXE_ID: 199, REPLICA_ACTION, {unified-logs-2, oldLeader: 2, [2, 3, 4] -> [1, 3, 4]}, COMPLETED}, {EXE_ID: 201, REPLICA_ACTION, {__consumer_offsets-14, oldLeader: 3, [3, 2, 4] -> [1, 2, 4]}, COMPLETED}, {EXE_ID: 203, REPLICA_ACTION, {__consumer_offsets-30, oldLeader: 2, [2, 4, 5] -> [2, 1, 5]}, COMPLETED}, {EXE_ID: 204, REPLICA_ACTION, {__consumer_offsets-0, oldLeader: 2, [2, 4, 3] -> [1, 4, 5]}, COMPLETED}, {EXE_ID: 206, REPLICA_ACTION, {unified-logs-19, oldLeader: 4, [4, 3, 5] -> [4, 1, 5]}, COMPLETED}, {EXE_ID: 207, REPLICA_ACTION, {__consumer_offsets-26, oldLeader: 3, [3, 4, 5] -> [3, 1, 5]}, COMPLETED}] (com.linkedin.kafka.cruisecontrol.executor.Executor)
[2018-06-22 16:09:14,460] INFO 80/100 (80.00%) partition movements completed. 57/57 (100.00%) MB have been moved. (com.linkedin.kafka.cruisecontrol.executor.Executor)
```

Please let me know if you need any more information. Given that this is an bug within Kafka, do you think it's possible to introduce a fix from the CC side of things, or will we have to wait for an updated version of Kafka?

**Comment by becketqin** [comment]
@ynasser @jeremydonahue Thanks for reporting the issue. It is probably better to upgrade Kafka. 

A few clarifications:

1. Currently CC does not wait for the URP to drop to 0 before it claims the rebalance has finished. Instead, it makes sure the leader and replica set of a partition meet the expectation. This is why CC showed that the rebalance has finished, but URP still exists.

2. It is a little weird that CC is more likely to trigger the problem than other rebalance tools. One possibility is that CC reassign the partitions more aggressively than the other tools, i.e. CC dynamically updates the reassignment. But I am not sure this is something CC should "fix".

**Comment by ynasser** [comment]
@jeremydonahue @becketqin As a follow up, we upgraded to 1.1 and after lots of aggressive rebalancing with CC, we haven't seen the `ReplicaFetcherThread` exception that caused the under-replicated partitions again.

**Comment by jeremydonahue** [comment]
@ynasser Thanks for the update! That implies that the [Kafka `ReplicaFetcherThread` issue (KAFKA-6649)](https://issues.apache.org/jira/browse/KAFKA-6649) is not the underlying cause of this problem, as 1.1.0 is listed as one of the affected versions. Right?

**Comment by efeg** [comment]
Closing the issue as this was a Kafka issue -- not Cruise Control.
