### ISSUE TITLE
Exclude compact topics from 

### ISSUE THREAD

**Issue by jlisam** [linkedin/cruise-control#238]
👋  again,

So about a week ago I opened this issue https://github.com/linkedin/cruise-control/issues/236 with regards to missing metrics in some of the topics. After a bit of trial and error, I noticed that these errors were cause whenever I had a `compact` topic in the cluster (other than` __consumer_offsets`). I would delete it and the errors would go away; cruise-control would work fine afterwards. Now, my question is how do I prevent this from happening again? We do have use cases where a compact topic makes sense. I initially tried setting this configuration `topics.excluded.from.partition.movement` to exclude topics but this happens after the metrics have been sampled from the broker https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java#L335 during the analyze state. Is there any other configurations that I am missing? How do I exclude my compact topics from being sampled?

Thank you so much 🙇

**Comment by efeg** [comment]
Hi @jlisam ,
The cleanup policy for CC generated topics should be configured as `delete`.
The patch https://github.com/linkedin/cruise-control/pull/83 has intended to ensure that `KafkaSampleStore` topics are explicitly configured with `delete` policy upon creation. Note that the if the default broker cleanup policy is `compact`, you also need to explicitly make sure that the topic to which Cruise Control metrics reporter should send messages is created with the `delete` cleanup policy -- the default metrics reporter topic is `__CruiseControlMetrics`.

Would you check to make sure that the following topics (if you are using the default configs for CC topic name) have cleanup policy set to `delete`?
1. `__CruiseControlMetrics`
2. `__KafkaCruiseControlPartitionMetricSamples`
3. `__KafkaCruiseControlModelTrainingSamples`

**Comment by jlisam** [comment]
hi @efeg !

Thank you for taking the time to respond to this. 

>  The patch #83 has intended to ensure that KafkaSampleStore topics are explicitly configured with delete policy upon creation. Note that if the default broker cleanup policy is compact, you also need to explicitly make sure that the topic to which Cruise Control metrics reporter should send messages is created with the delete cleanup policy -- the default metrics reporter topic is __CruiseControlMetrics.

Yeah, I read this a week ago and initially thought that the generated CC topics were set to `compact`. Unfortunately, I don't think that's the case:

> Would you check to make sure that the following topics (if you are using the default configs for CC topic name) have cleanup policy set to delete? ./kafka-topics.sh would be helpful to check the cleanup policy.

```
Topic:__KafkaCruiseControlPartitionMetricSamples	PartitionCount:32	ReplicationFactor:2	Configs:retention.ms=3600000,cleanup.policy=delete
Topic:__KafkaCruiseControlModelTrainingSamples	PartitionCount:32	ReplicationFactor:2	Configs:retention.ms=12000000,cleanup.policy=delete
Topic:__HydroCCMetrics 	PartitionCount:4	ReplicationFactor:3	Configs:
```
All the topics generated by CC have cleanup policy set to `delete`.  

To give you more information here is the full list of topics that are in my test cluster:

```
Topic:github.v1.ExampleDefaults	PartitionCount:4	ReplicationFactor:3	Configs:
Topic:github.v1.Example	PartitionCount:1	ReplicationFactor:1	Configs:delete.retention.ms=1000,cleanup.policy=compact
Topic:__consumer_offsets	PartitionCount:50	ReplicationFactor:3	Configs:segment.bytes=104857600,cleanup.policy=compact,compression.type=producer
Topic:__KafkaCruiseControlPartitionMetricSamples	PartitionCount:32	ReplicationFactor:2	Configs:retention.ms=3600000,cleanup.policy=delete
Topic:__KafkaCruiseControlModelTrainingSamples	PartitionCount:32	ReplicationFactor:2	Configs:retention.ms=12000000,cleanup.policy=delete
Topic:__HydroCCMetrics	PartitionCount:4	ReplicationFactor:3	Configs:
```

So when the above exists, my CC server starts complaining with the following output:

```java
2018-06-01 22:01:53,399] WARN Broker 1001 has [github.v1.Example] missing topics metrics and 1 missing partition metrics. (com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor)
[2018-06-01 22:01:53,399] TRACE Missing topics: [github.v1.Example] (com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor)
[2018-06-01 22:01:53,399] ERROR Error building partition metric sample for __consumer_offsets-13 (com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor)
java.lang.IllegalArgumentException: Broker metric ALL_TOPIC_REPLICATION_BYTES_OUT does not exist.
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor$BrokerLoad.brokerMetric(CruiseControlMetricsProcessor.java:374)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor$BrokerLoad.access$300(CruiseControlMetricsProcessor.java:296)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor.buildPartitionMetricSample(CruiseControlMetricsProcessor.java:255)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor.addPartitionMetricSamples(CruiseControlMetricsProcessor.java:126)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor.process(CruiseControlMetricsProcessor.java:87)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.getSamples(CruiseControlMetricsReporterSampler.java:125)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingFetcher.fetchSamples(SamplingFetcher.java:105)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingFetcher.fetchMetricsForAssignedPartitions(SamplingFetcher.java:85)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.call(MetricFetcher.java:24)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.call(MetricFetcher.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-06-01 22:01:53,400] ERROR Error building partition metric sample for __consumer_offsets-46 (com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor)
java.lang.IllegalArgumentException: Broker metric ALL_TOPIC_REPLICATION_BYTES_OUT does not exist.
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor$BrokerLoad.brokerMetric(CruiseControlMetricsProcessor.java:374)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor$BrokerLoad.access$300(CruiseControlMetricsProcessor.java:296)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor.buildPartitionMetricSample(CruiseControlMetricsProcessor.java:255)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor.addPartitionMetricSamples(CruiseControlMetricsProcessor.java:126)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsProcessor.process(CruiseControlMetricsProcessor.java:87)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.getSamples(CruiseControlMetricsReporterSampler.java:125)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingFetcher.fetchSamples(SamplingFetcher.java:105)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.SamplingFetcher.fetchMetricsForAssignedPartitions(SamplingFetcher.java:85)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.call(MetricFetcher.java:24)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher.call(MetricFetcher.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I went ahead and deleted `github.v1.Example` topic to see if this affected anything. Logs didn't show any more errors and metrics collections actually started working. I hope this paints a better picture. Let me know if you would like me to supply more information.

Thank you!

**Comment by jlisam** [comment]
@efeg , thank you 🙇 !
