### ISSUE TITLE
Cruise Control cannot find sampling topic matches __CruiseControlMetrics

### ISSUE THREAD

**Issue by wander3r** [linkedin/cruise-control#24]
i got this error when i try to start Cruise Control:

> [2017-09-06 09:48:26,651] INFO Kafka version : 0.10.1.0 (org.apache.kafka.common.utils.AppInfoParser)
[2017-09-06 09:48:26,651] INFO Kafka commitId : 3402a74efb23d1d4 (org.apache.kafka.common.utils.AppInfoParser)
Exception in thread "main" java.lang.IllegalStateException: Cruise Control cannot find sampling topic matches __CruiseControlMetrics in the target cluster.
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.configure(CruiseControlMetricsReporterSampler.java:175)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:207)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:110)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:62)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:61)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:112)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:75)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:47)

did i miss some configurations or should i create this topic manually?

**Comment by becketqin** [comment]
@wander3r Cruise Control Metrics Reporter will produce metrics to this topic. So if your Kafka cluster has auto.create.topics.enable set to true, there is no need to manually create this topic. Otherwise you may have to do so. We should probably let CruiseControlMetricsReporter to create this topic automatically, I'll file a new issue for this.

**Comment by sharepusher** [comment]
So cruise control do NOT create the topic automatically at present? I have to manually created __CruiseControlMetrics even I set enabled auto.create.topics.enable to True?

**Comment by sharepusher** [comment]
@becketqin I have enabled auto.create.topics.enable to true, and restarted the brokers, but why the __CruiseControlMetrics still not created automatically, I do NOT want to create the topic manually, what should I do to make it work? Thank you

**Comment by sharepusher** [comment]
does it mean, I have to compile the cruise control  in my target broker? then the __CruiseControlMetrics will be automatically created automatically? I don't wanna manually create it as it will be wired and hard to maintain if I tell my colleagues to make it on their new clusters

**Comment by sharepusher** [comment]
@wander3r have u solved this problem? created it manually? thanks.

**Comment by wander3r** [comment]
@sharepusher yes, i ceated this topic manually.otherwsie, the "metric.reporter.topic.pattern" configuration confused me in the first place, i thought there would be more than one topic to create.

**Comment by njpsanghani** [comment]
I had the same issue, but was resolved by this. set enabled auto.create.topics.enable to True or manually create the topic does the trick.
