### ISSUE TITLE
WARN Sampling did not finish in 120000 ms, skipping this sampling interval. (com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask)

### ISSUE THREAD

**Issue by bandishankar** [linkedin/cruise-control#29]
not able to sampling data 

WARN Sampling did not finish in 120000 ms, skipping this sampling interval. (com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask)

**Comment by becketqin** [comment]
@bandishankar Did you use the CruiseControlMetricsReporter on the broker side?

**Comment by bandishankar** [comment]
yes , I put jar inside  libs and changed the server properties to use it .

**Comment by bandishankar** [comment]
I am putting jar (cruise-control-metrics-reporter.jar)   under  "kafka/libs/ "
and adding in  server properties as   :   metrics.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

**Comment by bandishankar** [comment]
some more logs 


[2017-09-12 23:39:52,776] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:40:22,778] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:40:52,783] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:41:22,785] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:41:52,460] WARN Sampling did not finish in 120000 ms, skipping this sampling interval. (com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask)
[2017-09-12 23:41:52,785] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:42:22,789] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:42:52,793] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:43:22,797] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:43:52,459] WARN Sampling did not finish in 120000 ms, skipping this sampling interval. (com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask)
[2017-09-12 23:43:52,799] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:44:22,804] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:44:52,806] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:45:22,811] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-12 23:45:52,462] WARN Sampling did not finish in 120000 ms, skipping this sampling interval. (com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask)

**Comment by becketqin** [comment]
@bandishankar the configuration name on the broker is metric.reporters (singular).

**Comment by bandishankar** [comment]
But why it's not able to get snapshot , I waited for 30 minutes now .  still showing no relevent data 


{MonitorState: {state: SAMPLING(0.000% trained), NumValidWindows: (0/0) (NaN%), NumValidPartitions: 0/115 (0.000%), flawedPartitions: 0}, ExecutorState: {state: NO_TASK_IN_PROGRESS}, AnalyzerState: {isProposalReady: false, ReadyGaols: []}}

Monitored Windows:
{}

Goal Readiness:
                             RackAwareCapacityGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady
                                PotentialNwOutGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                         DiskUsageDistributionGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=true), NotReady
               NetworkInboundUsageDistributionGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
              NetworkOutboundUsageDistributionGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                          CpuUsageDistributionGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                    LeaderBytesInDistributionGoals, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                      TopicReplicaDistributionGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady
                           ReplicaDistributionGoal, (requiredNumSnapshots=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady

**Comment by bandishankar** [comment]
i have created only one broker with one topic .
Any specific setup to get snapshot.

**Comment by bandishankar** [comment]
added metric config as 
==================
kafka.metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
========================

getting error if i add simply as 

metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

**Comment by becketqin** [comment]
@bandishankar what error did you see when set metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter?

**Comment by yyb345** [comment]
@bandishankar  So, did you solve the problem ? I also encountered this problem which was still not solved

**Comment by bandishankar** [comment]
@becketqin  this is the error I am getting for 
metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter?

[2017-09-14 08:19:14,014] FATAL [Kafka Server 0], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.config.ConfigException: Configuration cruise.control.metrics.reporter.bootstrap.servers must be provided.
	at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:91)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:297)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:65)
	at kafka.Kafka.main(Kafka.scala)
[2017-09-14 08:19:14,016] INFO [Kafka Server 0], shutting down (kafka.server.KafkaServer)

**Comment by bandishankar** [comment]
@yyb345  just download new code and follow as given , it works now .

@becketqin  thanks
