### ISSUE TITLE
exception of "Index is out of range"

### ISSUE THREAD

**Issue by th3333** [linkedin/cruise-control#320]
We see a lot of errors like following and as a result cruisecontrol stopped to compute proposals (basically cruisecontrol stops working).

```
[2018-09-09 20:42:37,548] ERROR Unexpected exception (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)
java.lang.IllegalArgumentException: Index 5121751 is out of range [5121747, 5121747]
        at com.linkedin.cruisecontrol.common.WindowIndexedArrays.validateIndex(WindowIndexedArrays.java:45)
        at com.linkedin.cruisecontrol.monitor.sampling.aggregator.RawMetricValues.isExtrapolatedAtWindowIndex(RawMetricValues.java:174)
        at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.getWindowState(MetricSampleAggregator.java:450)
        at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.maybeUpdateAggregatorState(MetricSampleAggregator.java:441)
        at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.completeness(MetricSampleAggregator.java:277)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.validWindows(KafkaPartitionMetricSampleAggregator.java:191)
        at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.meetCompletenessRequirements(LoadMonitor.java:513)
        at com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector.run(GoalViolationDetector.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Can someone help investigate what may be the cause? Is there a way we could adjust the index size?

**Comment by chetann** [comment]
I also see this error every now and then, many a times it never stops throwing this error.

**Comment by kidkun** [comment]
can you try `state` endpoint with verbose=true? It will shows all the valid window CC currently have.

and can you check the version of CC you are running? I tried to check the code where exception is thrown in `GoalViolationDetector` find the lines seems not match.

**Comment by efeg** [comment]
`Index XXX is out of range` exceptions should have already been addressed in the current versions of Cruise Control. Feel free to reopen this issue if you experience a similar issue with the latest version.
