### ISSUE TITLE
Post Restful call causing issues?

### ISSUE THREAD

**Issue by chetann** [linkedin/cruise-control#322]
Hi, I am trying to add a broker, whenever I feel it ends up scewing complete CC set up.
I did try this https://<end point>/kafkacruisecontrol/add_broker?brokerid=106&goals=RackAwareGoal

And boom all my get/post calls throw null pointer exception. I did see the CC logs and it continuously keeps writing this.
```[2018-09-11 15:36:29,166] ERROR Unexpected exception (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)
java.lang.NullPointerException
[2018-09-11 15:36:29,166] ERROR Unexpected exception (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)
java.lang.NullPointerException
[2018-09-11 15:36:39,172] ERROR Unexpected exception (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)
java.lang.NullPointerException
[2018-09-11 15:36:39,172] ERROR Unexpected exception (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)
java.lang.NullPointerException
```
My Goals are showing fine though

```{MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (1/1) (100.000%), NumValidPartitions: 257/257 (100.000%), flawedPartitions: 0}, ExecutorState: {state: NO_TASK_IN_PROGRESS}, AnalyzerState: {isProposalReady: false, ReadyGoals: [NetworkInboundUsageDistributionGoal, CpuUsageDistributionGoal, PotentialNwOutGoal, NetworkInboundCapacityGoal, LeaderBytesInDistributionGoal, DiskCapacityGoal, ReplicaDistributionGoal, RackAwareGoal, TopicReplicaDistributionGoal, NetworkOutboundCapacityGoal, CpuCapacityGoal, DiskUsageDistributionGoal, NetworkOutboundUsageDistributionGoal, ReplicaCapacityGoal]}}

Monitored Windows [Window End_Time=Data_Completeness]:
{1536680100000=100.000%}

Goal Readiness:
                                     RackAwareGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                               ReplicaCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                  DiskCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                        NetworkInboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                       NetworkOutboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                                   CpuCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                           ReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                PotentialNwOutGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                         DiskUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
               NetworkInboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
              NetworkOutboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                          CpuUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                      TopicReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                     LeaderBytesInDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready


Extrapolated metric samples:
None```


I do see this stacktrace as well

```[2018-09-11 18:23:22,166] ERROR Error processing GET request '/partition_load' due to 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException'. (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)
java.util.concurrent.ExecutionException: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getAndMaybeReturnProgress(KafkaCruiseControlServlet.java:1072)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getPartitionLoad(KafkaCruiseControlServlet.java:515)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGet(KafkaCruiseControlServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.clusterModel(KafkaCruiseControl.java:378)
	at com.linkedin.kafka.cruisecontrol.async.GetClusterModelInRangeRunnable.getResult(GetClusterModelInRangeRunnable.java:36)
	at com.linkedin.kafka.cruisecontrol.async.GetClusterModelInRangeRunnable.getResult(GetClusterModelInRangeRunnable.java:15)
	at com.linkedin.kafka.cruisecontrol.async.OperationRunnable.run(OperationRunnable.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
``` 
Just trying to add in more information.
Not sure how to overcome Null pointer exceptions. Can you kindly help me out on what I am missing here.

**Comment by efeg** [comment]
Hi @chetann ,
Can you share 
1. the full stack trace (the shared stack trace seems to be missing the `1 more`, which is probably expanded in the logs the first time the exception was thrown), and 
2. the version of the Cruise Control (or the `HEAD` of your local repo)
for us to further investigate this? Do you still experience this issue?

**Comment by efeg** [comment]
Closing the issue as the latest version does not show a code path that can generate a `NPE`.
