### ISSUE TITLE
Get NotEnoughValidSnapshotsException when fetching /partition_load

### ISSUE THREAD

**Issue by jojohappy** [linkedin/cruise-control#37]
I'm new here. When I try to fetch partition_load, I get this exception
```
Error processing GET request '/partition_load'
com.linkedin.kafka.cruisecontrol.exception.NotEnoughValidSnapshotsException: The cluster model generation requires 1 snapshots with minimum monitored partitions percentage of 0.0. But there are only 0 valid snapshots available.
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.aggregateMetrics(LoadMonitor.java:509)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.clusterModel(LoadMonitor.java:377)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.clusterModel(KafkaCruiseControl.java:234)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getPartitionLoad(KafkaCruiseControlServlet.java:348)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGet(KafkaCruiseControlServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:745)
```
I don't mean why I have no valid snapshot, and I get these information in the log
```
[2017-09-22 18:40:55,346] INFO Rolled out new snapshot window 1506077100000, number of snapshots = 4 (com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator)
[2017-09-22 18:40:55,346] INFO Removed snapshot window 1506076200000, number of snapshots = 3 (com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator)
```
Any idea?
Thank you!

**Comment by becketqin** [comment]
@jojohappy What is does the /state endpoint say?

**Comment by jojohappy** [comment]
@becketqin 
```
{MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (1/1) (100.000%), NumValidPartitions: 309/309 (100.000%), flawedPartitions: 0}, ExecutorState: {state: NO_TASK_IN_PROGRESS}, AnalyzerState: {isProposalReady: true, ReadyGaols: [NetworkInboundUsageDistributionGoal, ReplicaDistributionGoal, LeaderBytesInDistributionGoals, CpuUsageDistributionGoal, TopicReplicaDistributionGoal, DiskUsageDistributionGoal, PotentialNwOutGoal, NetworkOutboundUsageDistributionGoal, RackAwareCapacityGoal]}}
```

**Comment by becketqin** [comment]
@jojohappy Hmm, I cannot reproduce this. What was the URL you used to query the partition load?

**Comment by jojohappy** [comment]
Hmm, I have got the partition resource utilization without time window. But it can not fetch partition resource utilization with the end clock time.
e.g
```
GET /kafkacruisecontrol/partition_load?resource=DISK&end=1506388177
```
It works
```
GET /kafkacruisecontrol/partition_load?resource=DISK&start=1506388177
```

I also found that the end clock time must be a timestamp in milliseconds and the end of snapshot window. 
```
GET /kafkacruisecontrol/partition_load?resource=DISK&end=1506389100000
```
So how can I find the snapshot window exist? Or I should not fetch partition resource utilization without end clock time?

Thank you~

**Comment by lifehacking** [comment]
i same error
[2018-03-09 16:27:51,988] ERROR Error processing GET request '/load' (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)
java.util.concurrent.ExecutionException: com.linkedin.kafka.cruisecontrol.exception.NotEnoughValidSnapshotsException: The cluster model generation requires 1 snapshots with minimum monitored partitions percentage of 0.0. But there are only 0 valid snapshots available.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getAndMaybeReturnProgress(KafkaCruiseControlServlet.java:1028)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getClusterLoad(KafkaCruiseControlServlet.java:525)
	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGet(KafkaCruiseControlServlet.java:282)


state：
{
  "AnalyzerState": {
    "isProposalReady": false,
    "readyGoals": []
  },
  "MonitorState": {
    "trainingPct": 0,
    "trained": "false",
    "numFlawedPartitions": 0,
    "monitoredWindows": {},
    "state": "RUNNING",
    "numTotalPartitions": 1629,
    "numMonitoredWindows": 0,
    "monitoringCoveragePct": 0,
    "numValidPartitions": 0
  },
  "ExecutorState": {
    "state": "NO_TASK_IN_PROGRESS"
  },
  "version": 1
}

**Comment by efeg** [comment]
`NotEnoughValidSnapshotsException` does not exist in the current version of CC.
