### ISSUE TITLE
KeeperErrorCode = NoAuth for /config/topics/__KafkaCruiseControlPartitionMetricSamples

### ISSUE THREAD

**Issue by choudhary001** [linkedin/cruise-control#507]
Hi,

I am using cruise-control v2.0.25 branch to setup cruise control for my kafka cluster. I am getting below error from zookeeper client when running cruise control. The zookeerper setup that I am connecting to has kerberos authenticated enabled. The kafka cluster also connects to this zookeeper setup and itself also uses kerberos for authentication.
I have setup the required properties as mentioned in the [guide](https://github.com/linkedin/cruise-control/tree/migrate_to_kafka_2_0). 

Could you please help out with what am i missing here. The kafka server and cruise control are both run using the same user.

`[2019-01-28 19:32:47,356] INFO EventThread shut down for session: 0x4687a65e0d6000c (org.apache.zookeeper.ClientCnxn)
[2019-01-28 19:32:47,357] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
Exception in thread "main" org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/topics/__KafkaCruiseControlPartitionMetricSamples
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:116)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:499)
	at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1449)
	at kafka.zk.KafkaZkClient.createOrSet$1(KafkaZkClient.scala:268)
	at kafka.zk.KafkaZkClient.setOrCreateEntityConfigs(KafkaZkClient.scala:278)
	at kafka.zk.AdminZkClient.createOrUpdateTopicPartitionAssignmentPathInZK(AdminZkClient.scala:98)
	at kafka.zk.AdminZkClient.createTopic(AdminZkClient.scala:56)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.ensureTopicCreated(KafkaSampleStore.java:364)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.ensureTopicsCreated(KafkaSampleStore.java:231)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.configure(KafkaSampleStore.java:164)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1104)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:104)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:157)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:113)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:106)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:67)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
`

Thanks,
Abhishek

**Comment by kidkun** [comment]
hey @choudhary001  
currently Cruise Control does not support [secure mechanism](https://github.com/linkedin/cruise-control/blob/0197b5316e35d9783bdb607fed411bd57474fc55/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java#L134). 

you are more than welcome to create a patch to make this configurable.

**Comment by choudhary001** [comment]
Thanks for confirming this @kidkun . How should i go about this if i want to create a patch. Is there any requirements or anything that developers already have in their roadmap?

**Comment by choudhary001** [comment]
How do I build cruise control to test out any changes? I followed the steps in https://github.com/linkedin/cruise-control#quick-start but the changes did not take effect.

**Comment by kidkun** [comment]
to run all the unit-test/integration test,  you can run command ` ./gradlew build` inside your CC repository

**Comment by efeg** [comment]
Closing the issue as @kidkun's response provides the necessary details.

**Comment by barryWarnock** [comment]
Sorry to raise a dead issue here but this is an issue I have run into as well. I need secure access to Zookeeper and have ACLs that only allow brokers to modify nodes, without the ability to securely connect to zookeeper I will be unable to use Cruise Control. Is this something anybody is working on or am I on my own to implement this? @choudhary001 did you get anywhere with your own implementation?

**Comment by efeg** [comment]
Hi @barryWarnock, the latest version of CC has the support for secure zookeeper.
Please see https://github.com/linkedin/cruise-control/wiki/Secure-zookeeper-configuration, and feel free to ping us if it doesn't help.

**Comment by nylend95** [comment]
Hi,
I too am sorry to raise this dead issue. I also get the same error message:
```
Exception in thread "main" org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/topics/__KafkaCruiseControlPartitionMetricSamples 
at org.apache.zookeeper.KeeperException.create(KeeperException.java:116) 
at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) 
at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:499) 
at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1449) 
```
I have followed https://github.com/linkedin/cruise-control/wiki/Secure-zookeeper-configuration , but that does not seem to resolve the issue. I think the reason for that is that we have set the property `zookeeper.set.acl=true` in our Kafka brokers. The way I read the code [apache/kafka/core/src/main/scala/kafka/zk/ZkData.scala](https://github.com/apache/kafka/blob/dd22b3f01b6bab41dce4d608f405ec6c78f7759e/core/src/main/scala/kafka/zk/ZkData.scala#L785) is that Kafka adds ZNode ACLs so only brokers can operate on the child nodes under `/config/topics`. 

My question, is therefore if Cruise Control supports this config in Kafka?
I think this is the same setup that you had, @barryWarnock . How did you proceed with issue?
