### ISSUE TITLE
Failed to start kafka server with latest cruise control metrics reporter

### ISSUE THREAD

**Issue by sharepusher** [linkedin/cruise-control#53]
I noticed some improvement recently, so I git cloned the latest cruise control, and get the metrics reporter after ./gradlew jar
I replaced the old one with the new reporter, and then failed to boot kafka anymore unless I comment out the report in server.properties. The kafka I'm using is kafka_2.11-0.11.0.0

[2017-10-12 16:35:33,939] INFO Socket connection established to xxxxxxx/xxxxxx:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-10-12 16:35:33,949] INFO Session establishment complete on server 10.27.235.137/10.27.235.137:2181, sessionid = 0x15ebd36d0090043, negotiated timeout = 40000 (org.apache.zookeeper.ClientCnxn)
[2017-10-12 16:35:33,951] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2017-10-12 16:35:34,067] INFO Cluster ID = hMzPvbduRpmD0ucSMOu5og (kafka.server.KafkaServer)
[2017-10-12 16:35:34,083] INFO Using default value of localhost:9090 for cruise.control.metrics.reporter.bootstrap.servers (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2017-10-12 16:35:34,083] INFO Using default value of PLAINTEXT for cruise.control.metrics.reporter.security.protocol (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2017-10-12 16:35:34,089] FATAL [Kafka Server 1], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:463)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:359)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:287)
	at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:109)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:297)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:65)
	at kafka.Kafka.main(Kafka.scala)
[2017-10-12 16:35:34,093] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)
[2017-10-12 16:35:34,096] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-10-12 16:35:34,101] INFO EventThread shut down for session: 0x15ebd36d0090043 (org.apache.zookeeper.ClientCnxn)
[2017-10-12 16:35:34,101] INFO Session: 0x15ebd36d0090043 closed (org.apache.zookeeper.ZooKeeper)
[2017-10-12 16:35:34,104] INFO [Kafka Server 1], shut down completed (kafka.server.KafkaServer)
[2017-10-12 16:35:34,104] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2017-10-12 16:35:34,107] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)

**Comment by becketqin** [comment]
@sharepusher Thanks for reporting the issue. #55 has resolved the problem.
