### ISSUE TITLE
cannot start kafka server after adding metric.reporters class

### ISSUE THREAD

**Issue by elhalouiMed** [linkedin/cruise-control#54]
i've just added the config in my kafka config file [server.properties]

metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

I have the error below
-------------------------------------------------------------

[2017-10-12 14:49:22,698] INFO Session establishment complete on server example.com/127.0.0.1:2181, sessionid = 0x15f10ad90270008, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2017-10-12 14:49:22,699] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2017-10-12 14:49:22,885] INFO Cluster ID = o0tbTctYTu27tXkfEqCp9w (kafka.server.KafkaServer)
[2017-10-12 14:49:22,899] INFO Using default value of localhost:9092 for cruise.control.metrics.reporter.bootstrap.servers (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2017-10-12 14:49:22,899] INFO Using default value of PLAINTEXT for cruise.control.metrics.reporter.security.protocol (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2017-10-12 14:49:22,905] FATAL [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:463)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:360)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:292)
	at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:109)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:297)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:89)
	at kafka.Kafka.main(Kafka.scala)

**Comment by becketqin** [comment]
@elhalouiMed Thanks for reporting the issue. #55 have solved the problem.
