### ISSUE TITLE
restart kafka server meet error

### ISSUE THREAD

**Issue by beyond555** [linkedin/cruise-control#56]
after set the metric.reporters to com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

i restart the kafka server, meet the problem as below,

[2017-10-11 10:21:52,359] FATAL [Kafka Server 0], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value. at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:463) at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453) at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62) at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75) at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:360) at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:288) at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:109) at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:297) at kafka.server.KafkaServer.startup(KafkaServer.scala:202) at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38) at kafka.Kafka$.main(Kafka.scala:65) at kafka.Kafka.main(Kafka.scala)

i add the bootstrap.servers in config/server.properties will not work.
how to solve it. kafka problem or version problem or sth else?

**Comment by becketqin** [comment]
#55 should have solved the issue for the default configuration. Or you can explicitly pass in the configuration of cruise.control.metrics.reporter.bootstrap.servers config.
