### ISSUE TITLE
ERROR Error processing POST request '/review' due to: 'null'

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#618]
**Whats Done**

1. Got the latest master code, compiled & started CC
2. (Missed Adding changes) No config changes were made to support the new 2-step bits in CC
3.  Made a request to `/review` and got 5XX error

```
[2019-03-29 08:47:15,692] ERROR Error processing POST request '/review' due to: 'null'. (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)
java.lang.NullPointerException
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.handleReviewRequest(KafkaCruiseControlServlet.java:339)                                                                                                               at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet$$Lambda$188/25539179.apply(Unknown Source)
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.lambda$syncRequest$181(KafkaCruiseControlServlet.java:442)                                                                                                            at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet$$Lambda$155/1477280931.apply(Unknown Source)
        at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager.insertFuturesByUserTaskId(UserTaskManager.java:379)
        at com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager.getOrCreateUserTask(UserTaskManager.java:191)
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.syncRequest(KafkaCruiseControlServlet.java:440)
        at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doPost(KafkaCruiseControlServlet.java:307)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
...
```

**What should happen**

CC Should send 4XX code indicating that this feature is not Supported/Enabled by config.

**Comment by nareshv** [comment]
did some more investigation and found that this happens when `json` param is not passed.

**Comment by nareshv** [comment]
Here is an example

```
$ curl http://localhost:9090/kafkacruisecontrol/review?json=true -X POST -s | jq .
{
  "RequestInfo": [],
  "version": 1
}
$ curl http://localhost:9090/kafkacruisecontrol/review -X POST
Error processing POST request '/review' due to: 'd != java.lang.String'.
```
NOTE: error message changed after i enabled the 2step in config
