### ISSUE TITLE
Sampling scheduler received Timeout exception when waiting for sampling to finish

### ISSUE THREAD

**Issue by andreydroid** [linkedin/cruise-control#702]
Hi,
Would really appreciate your help or any advice on this issue described bellow.

System info: a ~3600 partition/~30 topic cluster spanning over 6 brokers. Replication factor of 2. Processing about 200k msgs/sec. This cluster is used for log collection. Kafka v1.1.1, Cruise Control v 1.0.45

I've tried multiple metric sampling interval settings in the 60-600 second range, but that had no effect on the outcome. Consistently getting the timeout error (attached below). From reading the code I'm guessing (Scala is not my forte, regretfully) that sampling interval also defines the timeout, the longer the interval - the higher will be the number of samples that need to be processed when sampler thread spawns?

cruisecontrol.properties:
```
...
# The metric sampling interval in milliseconds
metric.sampling.interval.ms=300000 
# The partition metrics window size in milliseconds
partition.metrics.window.ms=60000 
# The number of partition metric windows to keep in memory
num.partition.metrics.windows=1
# The minimum partition metric samples required for a partition in each window
min.samples.per.partition.metrics.window=1
...
```

server.properties:
```
...
metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
cruise.control.metrics.reporter.bootstrap.servers=:6667
...
```

Brokers seem to start metrics reporter successfully and there are no errors or warnings in Kafka broker logs:
```
[2019-05-12 18:05:59,279] INFO Using default value of PLAINTEXT for cruise.control.metrics.reporter.security.protocol (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2019-05-12 18:05:59,281] INFO ProducerConfig values: 
        acks = all
        batch.size = 800000
        bootstrap.servers = [:6667]
        buffer.memory = 33554432
        client.id = CruiseControlMetricsReporter
        compression.type = gzip
        confluent.batch.expiry.ms = 30000
        connections.max.idle.ms = 540000
        enable.idempotence = false
        interceptor.classes = []
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 30000
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 5
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde
 (org.apache.kafka.clients.producer.ProducerConfig)
[2019-05-12 18:05:59,285] INFO Kafka version : 1.1.1-cp2 (org.apache.kafka.common.utils.AppInfoParser)
[2019-05-12 18:05:59,285] INFO Kafka commitId : 8c7c3bc6869f6125 (org.apache.kafka.common.utils.AppInfoParser)
[2019-05-12 18:05:59,288] INFO Added 0 Kafka metrics for Cruise Control metrics during initialization. (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2019-05-12 18:05:59,289] INFO Starting Cruise Control metrics reporter with reporting interval of 60000 ms. (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
```

Cruise Control logs show timeouts trying to finish sampling: 

```
[2019-05-12 19:45:30,602] ERROR Sampling scheduler received Timeout exception when waiting for sampling to finish (com.linkedin.kafka
.cruisecontrol.monitor.sampling.MetricFetcherManager)
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.fetchSamples(MetricFetcherManager.java:251)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.fetchPartitionMetricSamples(MetricFetcherManager.ja
va:199)
        at com.linkedin.kafka.cruisecontrol.monitor.task.SamplingTask.run(SamplingTask.java:56)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2019-05-12 19:45:30,603] INFO Finished sampling in 300001 ms. (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManage
r)
[2019-05-12 19:45:30,603] WARN Sampling did not finish in 300000 ms, skipping this sampling interval. (com.linkedin.kafka.cruisecontr
ol.monitor.task.SamplingTask)
[2019-05-12 19:45:30,603] INFO Kicking off partition metric sampling for time range [1557690030602, 1557690330603], duration 300001 m
s using 1 fetchers with timeout 300000 ms. (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager)
[2019-05-12 19:45:44,909] INFO Skipping proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafk
a.cruisecontrol.analyzer.GoalOptimizer)```

**Comment by efeg** [comment]
@andreydroid Does this issue still happen? Have you verified whether the metrics reporter can generate data to the metrics reporter topic -- i.e. if default configs are used, does `__CruiseControlMetrics` grow in size?

**Comment by efeg** [comment]
Closing this issue -- if it reoccurs, please verify the https://github.com/linkedin/cruise-control/issues/702#issuecomment-641668519 and feel free to reopen.
