### ISSUE TITLE
Cruise control not starting: Kafka cluster has less than 2 brokers

### ISSUE THREAD

**Issue by zandegran** [linkedin/cruise-control#718]
Cruise control is not starting. I have 3 brokers running.

`Caused by: java.lang.IllegalStateException: Kafka cluster has less than 2 brokers (brokers in cluster=0, zookeeper.connect=192.168.1.1:2183,192.168.1.1:2181,192.168.1.1:2182)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.ensureTopicsCreated(KafkaSampleStore.java:231)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.configure(KafkaSampleStore.java:170)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1171)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:104)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:157)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:113)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:113)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:70)
	at eventhub.cruisecontrol.CruiseControlProvider.<clinit>(CruiseControlProvider.java:45)
	... 44 more`

**Comment by efeg** [comment]
Hi @zandegran 
Based on this log: `Kafka cluster has less than 2 brokers (brokers in cluster=0, ...`, looks like CC cannot detect any brokers in the cluster. This typically indicates some misconfiguration.
Can you verify that (1) `bootstrap.servers` is configured correctly in `cruisecontrol.properties`, (2) you can `telnet` to the configured `ip` and `port`, and (3) try `localhost` rather than `192.168.1.1`?

**Comment by zandegran** [comment]
The configuration is correct. we are running multiple clusters in the same zookeeper ensemble with different chroot. Here is an example of our entire zookeeper tree [https://pastebin.com/KhZZLNU5](https://pastebin.com/KhZZLNU5)

**Comment by zandegran** [comment]
The problem is this cruise control is getting number of brokers here 
`int numberOfBrokersInCluster = kafkaZkClient.getAllBrokersInCluster().size();`
in KafkaSampleStore 
But getAllBrokersInCluster() uses the znode /brokers/ids to get the brokers. In our case it is at /kafka/1/brokers/ids

My current work around is start another cluster in the /brokers/ids and killing it after cruisecontrol starts.

Shall we add a flag in the config so that numberOfBrokersInCluster test can be skipped in KafkaSampleStore.ensureTopicsCreated??

**Comment by efeg** [comment]
@zandegran Would you check if this issue helps resolving your case: https://github.com/linkedin/cruise-control/issues/155?
-- i.e. in particular please see https://github.com/linkedin/cruise-control/issues/155#issuecomment-373679236

**Comment by zandegran** [comment]
Thanks @efeg it's starting now. But I find these errors in log.

`2019-05-23 14:05:32,302 +0200Z {} ERROR   RestModule com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore: Skip updating topic __KafkaCruiseControlPartitionMetricSamplesconfiguration due to failure:null.

2019-05-23 14:05:32,351 +0200Z {} ERROR   RestModule com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore: Skip updating topic __KafkaCruiseControlModelTrainingSamplesconfiguration due to failure:null.`

**Comment by efeg** [comment]
@zandegran 
The latest errors indicate runtime exceptions while attempting to set retention time, cleanup policy, and partition count of sample store topics, which have already been created before. Unfortunately, due to a logging bug, the full runtime exception is missing from the logs -- I created a patch to address that issue. 

Nevertheless, the only side affect of this issue is, if you have created sample store topics with different configs (e.g. retention time), and later changed the relevant CC configs to make some changes, such config changes might have failed to apply for these topics.

-- As a side note, I noticed that the name of your sample store topics are (1) `__KafkaCruiseControlPartitionMetricSamplesconfiguration` and (2) `__KafkaCruiseControlModelTrainingSamplesconfiguration`. Did you intentionally add the `configuration` prefix to the default sample store topic names? (i.e. this is not an issue if you intentionally changed names).

```
# The config for the Kafka sample store to save the partition metric samples
partition.metric.sample.store.topic=__KafkaCruiseControlPartitionMetricSamples

# The config for the Kafka sample store to save the model training samples
broker.metric.sample.store.topic=__KafkaCruiseControlModelTrainingSamples
```
