### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException on startup

### ISSUE THREAD

**Issue by LirioTech** [linkedin/cruise-control#731]
I've had cruise-control running on a standalone host for a while now, but it seems with the latest code I can't get it to start. 
I get this in the log file each time.
[2019-05-31 16:08:40,331] INFO COMMIT INFO: 0.1.50-SNAPSHOT---266623a66be3d9f29a0f2458ef6a53fc559470b7 (com.linkedin.kafka.cruisecontrol.KafkaCruiseControl)
Exception in thread "main" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.configure(CruiseControlMetricsReporterSampler.java:233)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1275)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:129)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:69)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:154)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:110)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:121)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:71)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)

The previous version I was using was:
INFO COMMIT INFO: 0.1.39---8ae97bfe48e5f21a242d0d462d112a2df22d808d 

keeping all configs the same and reverting back to the previous version i was using allows it to start as expected.

**Comment by kidkun** [comment]
@LirioTech  Thanks for reporting this!
It is a bug introduced recently and skipped our check(because we explicitly set config `reconnect.backoff.ms` in our environment), we will fix this soon and re-publish release `0.1.50` and `2.0.47`.
Sorry for the trouble brought to you.

**Comment by LirioTech** [comment]
unfortunately it's still receiving the same error for the new release.

[2019-06-03 11:41:03,906] INFO Kafka version : 0.11.0.2 (org.apache.kafka.common.utils.AppInfoParser)
[2019-06-03 11:41:03,906] INFO Kafka commitId : 73be1e1168f91ee2 (org.apache.kafka.common.utils.AppInfoParser)
Exception in thread "main" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.createConsumer(KafkaSampleStore.java:197)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.configure(KafkaSampleStore.java:156)
	at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1275)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:104)
	at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:154)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:110)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:119)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:71)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
