### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException on startup

### ISSUE THREAD

**Issue by LirioTech** [linkedin/cruise-control#734]
this was reported already in [731](https://github.com/linkedin/cruise-control/issues/731), which was fixed and closed, but it doesn't appear to be fixed. 

I added notes to that bug, but i figured this needs a new bug as well?

unfortunately it's still receiving the same error for the new release.

`
[2019-06-03 11:41:03,906] INFO Kafka version : 0.11.0.2 (org.apache.kafka.common.utils.AppInfoParser) [2019-06-03 11:41:03,906] INFO Kafka commitId : 73be1e1168f91ee2 (org.apache.kafka.common.utils.AppInfoParser) Exception in thread "main" java.lang.NullPointerException at java.util.Hashtable.put(Hashtable.java:460) at java.util.Properties.setProperty(Properties.java:166) at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.createConsumer(KafkaSampleStore.java:197) at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.configure(KafkaSampleStore.java:156) at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1275) at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:104) at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74) at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:154) at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:110) at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:119) at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:71) at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
`

to add to this a little, i uncommented the config for reconnect.backoff.ms to set it to 50 explicitly and received a different error.

`
[2019-06-03 12:09:13,108] INFO COMMIT INFO: 0.1.52-SNAPSHOT---cde921adb571f5c50f3afdb30770eddc29143c3b (com.linkedin.kafka.cruisecontrol.KafkaCruiseControl) Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long at com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler.configure(CruiseControlMetricsReporterSampler.java:222) at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1275) at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:129) at com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager.<init>(MetricFetcherManager.java:69) at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74) at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:154) at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:110) at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:119) at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:71) at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
`

**Comment by hack2learn** [comment]
Having same issue with version 2.0.48. When i comment in:

```
# The time to wait before reconnect to a given host.
reconnect.backoff.ms=50

I get same error as above and when i leave it commented out i get null pointer exception on startup.

**Comment by kidkun** [comment]
@LirioTech @hack2learn Really sorry for the trouble. The original bug is partially fixed. Will release the new version and deprecate the faulty version soon.

**Comment by hack2learn** [comment]
@kidkun thank you, appreciate it.
