### ISSUE TITLE
cruise-control-client should not swallow error codes

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#873]
# Background
`cruise-control` implements a REST API.

As such, there are all sorts of HTTP codes that it can return (for example, a [414](https://http.cat/414)).

# Issue
Unfortunately, `cruise-control-client`'s internal logic _always_ attempts to parse the response from `cruise-control` as JSON.

The implicit assumption here (that `cruise-control` will always return a text response, parseable as JSON) is incorrect.

One clear place where this is incorrect is if users of `cruise-control-client` tries to pass a too-long URI to `cruise-control`, to change the replication factor of lots of topics via the `topic_configuration` endpoint.

This results in the following ugly stack trace:  
```
Traceback (most recent call last):
  File "/export/apps/python/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/export/apps/python/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/thing.pyz/__main__.py", line 3, in <module>
  File "/usr/bin/thing.pyz/_bootstrap/__init__.py", line 181, in bootstrap
  File "/usr/bin/thing.pyz/_bootstrap/interpreter.py", line 52, in execute_interpreter
  File "/usr/bin/thing.pyz/_bootstrap/interpreter.py", line 29, in execute_content
  File "/usr/bin/thing.pyz/_bootstrap/interpreter.py", line 12, in _exec_function
  File "./rf_change_executor.py", line 145, in <module>
    main()
  File "/place/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/place/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/place/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/place/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./rf_change_executor.py", line 141, in main
    set_rf(fabric, tag, topic_regex, rf, moves=moves, execute=execute)
  File "./rf_change_executor.py", line 86, in set_rf
    response = json_responder.retrieve_response()
  File "/place/site-packages/cruisecontrolclient/client/Responder.py", line 125, in retrieve_response
    while 'progress' in response.json().keys():
  File "/place/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/place/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/place/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/place/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The offending line is, of course, 
```
  File "/place/site-packages/cruisecontrolclient/client/Responder.py", line 125, in retrieve_response
    while 'progress' in response.json().keys():
```

# Proposal
The `Responder` class in `cruise-control-client` should not falsely assume that `response.json()` will succeed.

It should probably still bubble up the `Requests.Response` to the caller, since the caller would need to examine this `Response` for its `status_code`

**Comment by tomncooper** [comment]
So would the preferred behaviour be for the CLI to raise the actual HTTP error code it received? 

`requests.Response` has a `raise_for_status()` method that raises a `requests.exceptions.HTTPError` for any non 2xx status. Just wondering if it would be better to do this in the `client/Responder` or if it should swallow it and pass some signal up to the calling method (which seems like a lot more work)?

**Comment by mgrubent** [comment]
It looks like #880 would obviate the issues raised here.

#880 allows for non-JSON responses from `cruise-control`, and if a `414` is received would print the following to CLI user (which is the body of the response from `cruise-control`):  
```text
<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
```

After #880, direct users of `cruise-control-client` would receive a `requests.Response` object (since `CruiseControlResponder` would not presume that the response contains valid JSON), which would have a `status_code` field.

It's not clear that a non-2xx response should always necessitate an exception, since `cruise-control` routinely returns `500`, for instance when it would not execute a proposal due to another ongoing proposal execution.
