### ISSUE TITLE
javax.security.auth.login.LoginException in SASL_PLAINTEXT

### ISSUE THREAD

**Issue by apellegr06** [linkedin/cruise-control#887]
Hello,

I have a problem on my kafka 1.0 with kerberos security (SASL_PLAINTEXT) and cruise control version 0.1.62. I have set the parameters cruise.control.metrics.reporter.bootstrap.servers to the secured SASL_PLAINTEXT listener and the cruise.control.metrics.reporter.security.protocol=SASL_PLAINTEXT, but when I start the kafka broker linked to cruise-control-metrics-reporter-0.1.62.jar, the broker stopped and I obtain the error :

org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner authentication information from the user

Have you an idea for that ?

And for information I also have a kafka 2.0 cluster with cruise control 2.0.59 and it works fine in SASL_PLAINTEXT

Thank you
Alain

**Comment by Sugaroverdose** [comment]
To tell client to use kerberos auth you must pass `sasl.mechanism=GSSAPI` setting to client, or in case of cruise-control it should looks like ```cruise.control.metrics.reporter.sasl.mechanism=GSSAPI```, it also requires that you pass JAAS setting into `cruise.control.metrics.reporter.sasl.jaas.config` which in result should look like this:
```cruise.control.metrics.reporter.sasl.jaas.config=cruise.control.metrics.reporter.sasl.jaas.config =com.sun.security.auth.module.Krb5LoginModule required \
  useKeyTab=true \
  storeKey=true \
  keyTab="/path/to/kafka_server.keytab" \
  principal="kafka/kafka1.hostname.com@EXAMPLE.COM";
```
or something like that, better description in kafka docs

**Comment by apellegr06** [comment]
Hello,

I have added :

cruise.control.metrics.reporter.sasl.jaas.config=/usr/hdp/current/kafka-broker/conf/kafka_jaas.conf
cruise.control.metrics.reporter.sasl.mechanism=GSSAPI

(I also try cruise.control.metrics.reporter.sasl.enabled.mechanisms=GSSAPI)

But it doesn't work, I have another error :

[2019-08-08 07:00:51,392] FATAL [KafkaServer id=1002] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:433)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291)
        at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(CruiseControlMetricsReporter.java:124)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:297)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:92)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.IllegalArgumentException: Login module not specified in JAAS config
        at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:66)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:88)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:78)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:104)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:61)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:86)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:390)

**Comment by apellegr06** [comment]
Thank you, it works fine just by adding the cruise.control.metrics.reporter.sasl.jaas.config parameter

**Comment by Sugaroverdose** [comment]
It's still better to enforce specific mechanism, just to be sure that unexpectedly changed default will not break anything (GSSAPI is default for SASL atm)
