### ISSUE TITLE
com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter ClassNotFoundException exception occurred

### ISSUE THREAD

**Issue by ZSH9053** [linkedin/cruise-control#905]
hello I am new to CruiseControl. I want to monitor our kafka clusters . 
When I setup CruiseControl according to Wiki,I got some problem.
I set metric.reporters = com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
in my kafka server.propertities file, and I start kafka-server,got an error
[2019-08-15 16:20:39,257] INFO [TransactionCoordinator id=3] Starting up. (kafka.coordinator.transaction.TransactionCoordinator)
[2019-08-15 16:20:39,259] INFO [TransactionCoordinator id=3] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2019-08-15 16:20:39,266] INFO [Transaction Marker Channel Manager 3]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2019-08-15 16:20:39,358] ERROR [KafkaServer id=3] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter ClassNotFoundException exception occurred
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:357)
        at kafka.server.DynamicMetricsReporters.createReporters(DynamicBrokerConfig.scala:736)
        at kafka.server.DynamicMetricsReporters.<init>(DynamicBrokerConfig.scala:685)
        at kafka.server.DynamicBrokerConfig.addReconfigurables(DynamicBrokerConfig.scala:219)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:316)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.ClassNotFoundException: com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:339)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:328)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:355)

How do I fix this problem ?

**Comment by kidkun** [comment]
Hey @ZSH9053 , did you copy cruise-control-metrics-reporter's jar to  Kafka server dependency jar folder? 
Please check step 1 [ at quick start](https://github.com/linkedin/cruise-control#quick-start).

**Comment by ZSH9053** [comment]
@kidkun
when I finish 
./gradlew jar
my kafka directory has not "core/build/dependant-libs-SCALA_VERSION/"
here is my kafka directory  

-rw-r--r-- 1 root root  4228589 Jul  7  2018 kafka_exporter-1.2.0.linux-amd64.tar.gz
-rw-rw-r-- 1 root root    32216 May 14 00:10 LICENSE
-rw-rw-r-- 1 root root      336 May 14 00:10 NOTICE
drwxr-xr-x 3 root root     4096 May 14 00:18 bin
drwxr-xr-x 2 root root     4096 May 14 00:18 site-docs
drwxrwxr-x 2 2000 2000     4096 Aug 15 15:05 kafka_exporter-1.2.0.linux-amd64
drwxr-xr-x 2 root root     4096 Aug 16 09:59 libs
drwxr-xr-x 2 root root     4096 Aug 16 09:59 config
drwxr-xr-x 2 root root     4096 Aug 16 10:00 logs
-rw------- 1 root root 42505549 Aug 16 10:00 nohup.out
[root@ylf-kafka-service-sit-01 kafka_2.12-2.2.1]#


Can you tell me where is the "core/build/dependant-libs-SCALA_VERSION/"
thanks

**Comment by kidkun** [comment]
@ZSH9053 
I just tried pulling a fresh trunk branch of apache/kafka and run `./gradlew clean && ./gradlew jar`
what I get is 

> kdu-mn1:dependant-libs-2.12.9 kdu$ pwd
> /Users/kdu/workspace/kafka/core/build/dependant-libs-2.12.9

I am wondering it has something to do with the Kafka distribution, did you get Kafka from one of the release at https://github.com/apache/kafka/releases?

**Comment by efeg** [comment]
Closing the issue as  https://github.com/linkedin/cruise-control/issues/905#issuecomment-522791101 provides the steps to resolve it -- i.e. regarding missing `core/build/dependant-libs-SCALA_VERSION/` directory.
