### ISSUE TITLE
Null Borker_id Exception

### ISSUE THREAD

**Issue by recao** [linkedin/cruise-control#98]
Hi, we are testing CruiseControl on our production Kafka clusters, and got following error message: 

[2017-12-27 22:42:16,678] FATAL  (kafka.Kafka$)
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter.configure(**CruiseControlMetricsReporter.java:111**)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:239)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:925)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:779)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:776)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
        at kafka.Kafka$.main(Kafka.scala:58)
        at kafka.Kafka.main(Kafka.scala)

By look at source code, seems CruiseControlMetricsReporter needs to get Broker_id from KafkaConfig object, which reads from server.properties file. 

The problem is our production Kafka cluster uses automatic Broker-ids generated by ZooKeeper, so there is no such "broker.id" attribute in the server.properties file, which causes the FATAL error above. Any suggestions to unblock ourselves in this scenario? Thanks!

Ren

**Comment by becketqin** [comment]
@recao Which Kafka version are you running? Kafka 0.10.2.0+ should have passed the broker id to the metrics reporter. If your Kafka server is before 0.10.2.0, you may have to specify the broker id explicitly in the server.properties file. Hopefully the broker id will only change rarely. So once set it will not change.
